GnarledRidge_EventObjects::
	object_event 1, EVENT_OBJ_GFX_BERRY_TREE, 0, 9, 21, 3, MOVEMENT_TYPE_BERRY_TREE_GROWTH, 0, 0, 0, 25, S_BerryTree, 0
	object_event 2, EVENT_OBJ_GFX_BERRY_TREE, 0, 10, 21, 3, MOVEMENT_TYPE_BERRY_TREE_GROWTH, 0, 0, 0, 26, S_BerryTree, 0
	object_event 3, EVENT_OBJ_GFX_BERRY_TREE, 0, 11, 21, 3, MOVEMENT_TYPE_BERRY_TREE_GROWTH, 0, 0, 0, 66, S_BerryTree, 0
	object_event 4, EVENT_OBJ_GFX_BERRY_TREE, 0, 12, 21, 3, MOVEMENT_TYPE_BERRY_TREE_GROWTH, 0, 0, 0, 67, S_BerryTree, 0
	object_event 5, EVENT_OBJ_GFX_YOUNGSTER, 0, 15, 38, 3, MOVEMENT_TYPE_FACE_DOWN_AND_RIGHT, 0, 0, 1, 3, GnarledRidge_EventScript_Trainer1, 0
	object_event 6, EVENT_OBJ_GFX_HIKER, 0, 23, 34, 3, MOVEMENT_TYPE_FACE_DOWN_UP_AND_RIGHT, 0, 0, 1, 3, GnarledRidge_EventScript_Trainer2, 0
	object_event 7, EVENT_OBJ_GFX_MANIAC, 0, 6, 27, 3, MOVEMENT_TYPE_FACE_RIGHT, 0, 0, 1, 3, GnarledRidge_EventScript_Trainer3, 0
	object_event 8, EVENT_OBJ_GFX_ITEM_BALL, 0, 7, 37, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, GnarledRidge_EventScript_Item1, FLAG_ITEM_GNARLED_RIDGE_1
	object_event 9, EVENT_OBJ_GFX_PUSHABLE_BOULDER, 0, 20, 16, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, S_PushableBoulder, FLAG_TEMP_13

GnarledRidge_MapWarps::

GnarledRidge_MapCoordEvents::

GnarledRidge_MapBGEvents::

GnarledRidge_MapEvents::
	map_events GnarledRidge_EventObjects, 0x0, 0x0, 0x0
