GnarledRidge_Text_Trainer1Meet::
    .string "Rumor is a huge dragon lives up here.\n"
    .string "Heard anything about it?$"

GnarledRidge_Text_Trainer1Beat::
    .string "You’re stronger than a dragon!$"

GnarledRidge_Text_Trainer1Chat::
    .string "I wonder if there really\n"
    .string "are any dragons out here...$"

GnarledRidge_Text_Trainer2Meet::
    .string "I’m off work today.\n"
    .string "Perfect time for a battle!$"

GnarledRidge_Text_Trainer2Beat::
    .string "Hey, not bad!$"

GnarledRidge_Text_Trainer2Chat::
    .string "I work as a software developer.\p"
    .string "I spend my off-days making\n"
    .string "sure my body is in shape.$"

GnarledRidge_Text_Trainer3Meet::
    .string "Out here, I’ve put together the optimal\n"
    .string "team. Behold!$"

GnarledRidge_Text_Trainer3Beat::
    .string "I didn’t say battle-optimal!$"

GnarledRidge_Text_Trainer3Chat::
    .string "My buddy says I should use\n"
    .string "more than one type of Pokémon.\p"
    .string "I say it doesn’t matter as\n"
    .string "long as I can make it work.$"
