LilycoveCity_CoveLilyMotel_2F_Text_186FE7:: @ 8186FE7
	.string "I'm the Game Designer.\p"
	.string "Oh, is that right?\n"
	.string "You're working on a Pokédex?\p"
	.string "It's tough trying to complete it,\n"
	.string "but don't give up.\p"
	.string "If you do complete it, please come\n"
	.string "show me.$"

LilycoveCity_CoveLilyMotel_2F_Text_18708F:: @ 818708F
	.string "Wow! That's awesome!\n"
	.string "Yep, it's totally awesome!\p"
	.string "This Pokédex is completely filled!\n"
	.string "You really must love Pokémon!\p"
	.string "I'm so impressed!\p"
	.string "Let me give you something in\n"
	.string "recognition of your feat!$"

LilycoveCity_CoveLilyMotel_2F_Text_187149:: @ 8187149
	.string "Me? You're talking to me?\n"
	.string "I'm the Programmer.\p"
	.string "I wonder what the Slots are\n"
	.string "like here.$"

LilycoveCity_CoveLilyMotel_2F_Text_18719E:: @ 818719E
	.string "I'm the Graphic Artist! Aren't the\n"
	.string "Pokémon of Hoenn interesting?$"

LilycoveCity_CoveLilyMotel_2F_Text_18729A:: @ 818729A
	.string "The sea breeze tickles my heart.\n"
	.string "It feels wonderful here!$"

LilycoveCity_CoveLilyMotel_2F_Text_1872D4:: @ 81872D4
	.string "You never know when and where\n"
	.string "people will challenge you.\p"
	.string "That's why I never leave home without\n"
	.string "my hacked 3DS.$"
