Route120_Text_171827:: @ 8171827
	.string "STEVEN: Hm? {PLAYER}{KUN}, hi.\n"
	.string "It's been a while.\p"
	.string "There's something here that you can't\n"
	.string "see, right?\p"
	.string "Now, if I were to use this device on\n"
	.string "the invisible obstacle...\p"
	.string "No, no. Rather than describing it,\n"
	.string "I should just show you.\l"
	.string "That would be more fun.\p"
	.string "{PLAYER}{KUN}, are your Pokémon ready for\n"
	.string "battle?$"

Route120_Text_17193D:: @ 817193D
	.string "STEVEN: No?\p"
	.string "I'll wait here, so you can get ready.$"

Route120_Text_17196F:: @ 817196F
	.string "STEVEN: {PLAYER}{KUN}, are your Pokémon\n"
	.string "ready for battle?$"

Route120_Text_1719A0:: @ 81719A0
	.string "STEVEN: {PLAYER}{KUN}, show me your true\n"
	.string "power as a Trainer!$"

Route120_Text_1719D4:: @ 81719D4
	.string "Steven used the Devon Scope.\p"
	.string "An invisible Pokémon became completely\n"
	.string "visible!\p"
	.string "The startled Pokémon attacked!$"

Route120_Text_171A40:: @ 8171A40
	.string "STEVEN: I see...\n"
	.string "Your battle style is intriguing.\p"
	.string "Your Pokémon have obviously grown\n"
	.string "since I first met you in Dewford.\p"
	.string "I'd like you to have this\n"
	.string "Devon Scope.\p"
	.string "Who knows, there may be other\n"
	.string "concealed Pokémon.$"

Route120_Text_171B0E:: @ 8171B0E
	.string "STEVEN: {PLAYER}{KUN}.\p"
	.string "I enjoy seeing Pokémon and Trainers\n"
	.string "who strive together.\p"
	.string "I think you're doing great.\p"
	.string "Well, let's meet again somewhere.$"

Route119_Text_171B93:: @ 8171B93
Route120_Text_171B93:: @ 8171B93
	.string "Something unseeable is in the way.$"

Route119_Text_171BB6:: @ 8171BB6
	.string "Something unseeable is in the way.\p"
	.string "Want to use the Devon Scope?$"

Route119_Text_171BF6:: @ 8171BF6
	.string "{PLAYER} used the Devon Scope.\p"
	.string "An invisible Pokémon became completely\n"
	.string "visible!\p"
	.string "The startled Pokémon attacked!$"

Route120_Text_171C5E:: @ 8171C5E
	.string "ROUTE 120\n"
	.string "{0x7B} FORTREE CITY$"

Route120_Text_171C77:: @ 8171C77
	.string "{0x7C} ROUTE 121\n"
	.string "{0x7B} ROUTE 120$"

Route120_Text_EndOfBeta::
    .string "hey beta's over here, rest is\n"
    .string "under construction, go home$"
