Route112_Text_16FDF0:: @ 816FDF0
	.string "Grumble...\p"
	.string "What happened to the others who went\n"
	.string "to Fallarbor? They're late...$"

Route112_Text_16FE3E:: @ 816FE3E
	.string "Grumble...\p"
	.string "I'd like to ride the Cable Car to the\n"
	.string "top, too..$"

Route112_Text_16FE7A:: @ 816FE7A
	.string "Eh, I'd like to get to Mauville, but if\n"
	.string "I went down these ledges, it'd be no\l"
	.string "easy matter to get back to Lavaridge.$"

Route112_Text_16FEED:: @ 816FEED
	.string "MT. CHIMNEY CABLE CAR\n"
	.string "“A short walk {0x79} way!”$"

Route112_Text_16FF19:: @ 816FF19
	.string "MT. CHIMNEY\p"
	.string "“For Lavaridge Town or the summit,\n"
	.string "please take the Cable Car.”$"

Route112_Text_16FF64:: @ 816FF64
	.string "ROUTE 112\n"
	.string "{0x7B} LAVARIDGE TOWN$"
