FortreeCity_Mart_Text_1861EF:: @ 81861EF
	.string "Super Repel lasts a long time, and\n"
	.string "it gets the job done.\p"
	.string "It's much better than an ordinary\n"
	.string "Repel.$"

FortreeCity_Mart_Text_186251:: @ 8186251
	.string "I always stock up on more items than\n"
	.string "I'm sure I'll need.\p"
	.string "You never know what might happen.\n"
	.string "Better to be safe than sorry!$"

FortreeCity_Mart_Text_1862CA:: @ 81862CA
	.string "A Rare Candy makes a Pokémon grow\n"
	.string "immediately by one level.$"
