LavaridgeTown_Mart_Text_176DA6:: @ 8176DA6
	.string "Use X Speed to add to a Pokémon's\n"
	.string "Speed in battle.\p"
	.string "That will help it get in the first\n"
	.string "strike - a decided advantage!$"

LavaridgeTown_Mart_Text_176E1A:: @ 8176E1A
	.string "On Mt. Chimney's peak, there's a local\n"
	.string "specialty that you can buy only there.\p"
	.string "Give it to a Pokémon - it will be elated.$"
