MossdeepCity_House4_Text_18E0E3:: @ 818E0E3
	.string "My little brother says he likes to go\n"
	.string "find people's Secret Bases.$"

MossdeepCity_House4_Text_18E125:: @ 818E125
	.string "My little brother says he likes to\n"
	.string "visit people's Secret Bases and have\l"
	.string "Pokémon battles.$"

MossdeepCity_House4_Text_18E17E:: @ 818E17E
	.string "Was it you who made a Secret Base in\n"
	.string "{STR_VAR_1}?$"

MossdeepCity_House4_Text_18E1A7:: @ 818E1A7
	.string "You should make a Secret Base\n"
	.string "somewhere. I'll go find it!$"

MossdeepCity_House4_Text_18E1E1:: @ 818E1E1
	.string "DELCATTY: Miyaan?$"
