LilycoveCity_DepartmentStore_1F_Text_18BFB5:: @ 818BFB5
	.string "Welcome to Lilycove Department Store.$"

LilycoveCity_DepartmentStore_1F_Text_18BFDB:: @ 818BFDB
	.string "Whenever I come to the Department\n"
	.string "Store, I always end up buying all sorts\l"
	.string "of things because it's so fun.$"

LilycoveCity_DepartmentStore_1F_Text_18C044:: @ 818C044
	.string "Today, my mom is going to buy me some\n"
	.string "nice furniture.$"

LilycoveCity_DepartmentStore_1F_Text_18C07A:: @ 818C07A
	.string "I'm buying something for my Azumarill\n"
	.string "as a reward for winning a Contest.$"

LilycoveCity_DepartmentStore_1F_Text_18C0C3:: @ 818C0C3
	.string "AZUMARILL: Maririroo!$"

LilycoveCity_DepartmentStore_1F_Text_18C0D9:: @ 818C0D9
	.string "1F: SERVICE COUNTER\n"
	.string "    LOTTERY CORNER\p"
	.string "2F: TRAINER'S ZONE\p"
	.string "3F: BATTLE COLLECTION\p"
	.string "4F: TM CORNER\p"
	.string "5F: POKé DOLL FLOOR\p"
	.string "ROOFTOP: ROOFTOP PLAZA$"

LilycoveCity_DepartmentStore_1F_Text_ElevatorOutOfOrder::
	.string "Elevator's out of order, sorry.\n"
    .string "It'll be a while before it's working.\p"
    .string "You're a trainer, right? Maybe stop\n"
    .string "by again after beating Fortree's Gym.\p"
    .string "We should have the place fixed up by\n"
    .string "the time you get back.$"
