GraniteCave_1F_Text_194917:: @ 8194917
	.string "Hey, you.\n"
	.string "It gets awfully dark ahead.\l"
	.string "It'll be tough trying to explore.\p"
	.string "That guy who came by earlier...\n"
	.string "Steven, I think it was.\p"
	.string "He knew how to use Flash, so he ought\n"
	.string "to be all right, but...\p"
	.string "Well, for us Hikers, helping out those\n"
	.string "that we meet is our motto.\p"
	.string "Here you go, I'll pass this on to you.$"

GraniteCave_1F_Text_194A3E:: @ 8194A3E
	.string "Teach that hidden move Flash to a\n"
	.string "Pokémon and use it.\p"
	.string "It lights up even the inky darkness\n"
	.string "of caves.\p"
	.string "But, to use it, you need the Gym Badge\n"
	.string "from Dewford's Pokémon Gym.$"
