Route124_DivingTreasureHuntersHouse_Text_Intro::
    .string "They call me the Ball Maniac.\n"
    .string "Wanna see some nice...Balls?$"

Route124_DivingTreasureHuntersHouse_Text_Outro::
    .string "Come back whenever you need\n"
    .string "some high-quality Balls.$"


Route124_DivingTreasureHuntersHouse_Text_19F6C5:: @ 819F6C5
	.string "Wanted item              Trade item\n"
	.string " RED SHARD           {0x7B}{0x7C} FIRE STONE\p"
	.string "Wanted item              Trade item\n"
	.string " YELLOW SHARD     {0x7B}{0x7C} THUNDERSTONE\p"
	.string "Wanted item              Trade item\n"
	.string " BLUE SHARD         {0x7B}{0x7C} WATER STONE\p"
	.string "Wanted item              Trade item\n"
	.string " GREEN SHARD       {0x7B}{0x7C} LEAF STONE$"
