Route124_DivingTreasureHuntersHouse_Text_Intro::
    .string "They call me the Ball Maniac.\n"
    .string "Wanna see some nice...Balls?$"

Route124_DivingTreasureHuntersHouse_Text_FamiliarIntro::
    .string "Hey, nice to see you again.\n"
    .string "Still interested in my...Balls?$"

Route124_DivingTreasureHuntersHouse_Text_SpotGSBall::
    .string "They call me the Ball Maniac.\n"
    .string "Hang on a sec...\p"
    .string "That shiny thing you've got there...\n"
    .string "Is'sat the GS Ball?\p"
    .string "You gotta let me take a look at that!$"

Route124_DivingTreasureHuntersHouse_Text_Examine::
    .string "Sweeeet. Let's take a looksee...$"

Route124_DivingTreasureHuntersHouse_Text_Examine2::
    .string ".....\n"
    .string ".....\p"
    .string "This is....a lot of locks...\p"
    .string "If I...twist this...here...\p"
    .string ".....\n"
    .string ".....$"

Route124_DivingTreasureHuntersHouse_Text_Examine3::
    .string "Alright. This thing is...fascinating.\p"
    .string "So, there's a Pokemon in here.\n"
    .string "Still conscious and aware.\p"
    .string "That said, there were also a lot of\n"
    .string "locks and faults.\p"
    .string "I fixed most of them...but there's\n"
    .string "one issue that's more of a design flaw.\p"
    .string "This ball can't release.\p"
    .string "Whatever's inside will only come out\n"
    .string "when and if it feels like it.\p"
    .string "If you get it somewhere that it feels\n"
    .string "comfy, it might emerge.\p"
    .string "Go take it outside somewhere. It sure\n"
    .string "ain't liking my shack here.$"

Route124_DivingTreasureHuntersHouse_Text_Decline::
    .string "Tch...I'm not gonna break it.\p"
    .string "Well, while you're here, wanna\n"
    .string "check out my Balls?$"

Route124_DivingTreasureHuntersHouse_Text_Outro::
    .string "Come back whenever you need\n"
    .string "some high-quality Balls.$"


Route124_DivingTreasureHuntersHouse_Text_19F6C5:: @ 819F6C5
	.string "Wanted item              Trade item\n"
	.string " RED SHARD           {0x7B}{0x7C} FIRE STONE\p"
	.string "Wanted item              Trade item\n"
	.string " YELLOW SHARD     {0x7B}{0x7C} THUNDERSTONE\p"
	.string "Wanted item              Trade item\n"
	.string " BLUE SHARD         {0x7B}{0x7C} WATER STONE\p"
	.string "Wanted item              Trade item\n"
	.string " GREEN SHARD       {0x7B}{0x7C} LEAF STONE$"
