RustboroCity_Gym_Text_183A4B:: @ 8183A4B
	.string "Yo, how's it going?\p"
	.string "Listen, my friend!\n"
	.string "Would you like to become the Champion?\p"
	.string "I'm no Trainer, not me, but I can\n"
	.string "sure give you winning advice.\p"
	.string "That's settled, then! We'll aim for the\n"
	.string "Pokémon Championship together!\p"
	.string "It's your job as a Trainer to collect\n"
	.string "Gym Badges, am I right?\p"
	.string "But Gym Leaders aren't pushovers!\p"
	.string "And that's where I come in!\n"
	.string "I'm here to provide expert advice!\p"
	.string "Roxanne, the Gym Leader, is a user\n"
	.string "of Rock-type Pokémon.\p"
	.string "TheRock type is very durable, but\n"
	.string "it can't stand Water-type and\l"
	.string "Grass-type moves.\p"
	.string "Come see me afterwards, if you beat\n"
	.string "the Gym Leader.\p"
	.string "Well, go for it!$"

RustboroCity_Gym_Text_183C90:: @ 8183C90
	.string "Whoa! What a breathtaking victory!\n"
	.string "My cheering must've worked!\p"
	.string "Great!\n"
	.string "Check your Trainer Card.\p"
	.string "The Stone Badge you got should be\n"
	.string "properly recorded on it.\p"
	.string "In other words...\p"
	.string "You've climbed the first step on\n"
	.string "the stairs to the Championship!\p"
	.string "That's got to feel awesome!$"

RustboroCity_Gym_Text_183D99:: @ 8183D99
	.string "Don't take us Gym Trainers lightly!\n"
	.string "I'll show you why we're better!$"

RustboroCity_Gym_Text_183DDD:: @ 8183DDD
	.string "You were too good for me...$"

RustboroCity_Gym_Text_183DF9:: @ 8183DF9
	.string "You haven't seen anything of the Rock\n"
	.string "type's terrifying power!$"

RustboroCity_Gym_Text_183E38:: @ 8183E38
	.string "If you can't beat me, you won't stand\n"
	.string "a chance against Roxanne!$"

RustboroCity_Gym_Text_183E78:: @ 8183E78
	.string "Wow! You've got some potential!$"

RustboroCity_Gym_Text_183E98:: @ 8183E98
	.string "Roxanne is stronger than me by\n"
	.string "several times.\p"
	.string "You'd better be on your guard!$"

RustboroCity_Gym_Text_183EE5:: @ 8183EE5
	.string "Hello, I am Roxanne, the Rustboro\n"
	.string "Pokémon Gym Leader.\p"
	.string "I became a Gym Leader so that I may\n"
	.string "apply what I learned at the Pokémon\l"
	.string "Trainer's School in battle.\p"
	.string "Would you kindly demonstrate how you\n"
	.string "battle, and with which Pokémon?$"

RustboroCity_Gym_Text_183FC4:: @ 8183FC4
	.string "So...\n"
	.string "I lost...\p"
	.string "It seems that I still have much more\n"
	.string "to learn...\p"
	.string "I understand.\p"
	.string "The Pokémon League's rules state\n"
	.string "that Trainers are to be given this\l"
	.string "if they defeat a Gym Leader.\p"
	.string "Please accept the official Pokémon\n"
	.string "League Stone Badge.$"

RustboroCity_Gym_Text_1840AB:: @ 81840AB
	.string "{PLAYER} received the Stone Badge\n"
	.string "from Roxanne.$"

RustboroCity_Gym_Text_1840D5:: @ 81840D5
	.string "The Stone Badge proves that you've\n"
	.string "triumphed over the Rustboro Gym.\p"
	.string "It also enables your Pokémon to use\n"
	.string "the HM move Cut outside of battle.\p"
	.string "Please take this with you, too.$"

RustboroCity_Gym_Text_184170:: @ 8184170
	.string "That TM76 contains Stealth Rock.\p"
	.string "It inflicts damage over the rourse of\n"
	.string "a long battle to the entire team.\p"
	.string "It's potent in long battles, but\n"
	.string "do think before using it.$"

RustboroCity_Gym_Text_184252:: @ 8184252
	.string "Since you are so strong, you should\n"
	.string "challenge other Gym Leaders.\p"
	.string "By battling many Trainers, you should\n"
	.string "learn many things.$"

RustboroCity_Gym_Text_1842CC:: @ 81842CC
	.string "RUSTBORO CITY POKéMON GYM$"

RustboroCity_Gym_Text_1842E6:: @ 81842E6
	.string "RUSTBORO CITY POKéMON GYM\p"
	.string "ROXANNE'S CERTIFIED TRAINERS:\n"
	.string "{PLAYER}$"
