SlateportCity_Mart_Text_180730:: @ 8180730
	.string "The Market does have some interesting\n"
	.string "merchandise.\p"
	.string "But there are some items you can only\n"
	.string "get at a Poké Mart.$"

SlateportCity_Mart_Text_18079D:: @ 818079D
	.string "A Great Ball is better than a Poké Ball\n"
	.string "at catching Pokémon.\p"
	.string "With this, I should be able to get that\n"
	.string "elusive Pokémon...$"
