AlteringCave4F_EventObjects::
	object_event 1, EVENT_OBJ_GFX_MEWTWO, 0, 17, 6, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, AlteringCave4F_EventScript_Mewtwo, FLAG_HIDE_MEWTWO

AlteringCave4F_MapWarps::
	warp_def 17, 13, 0, 1, MAP_ALTERING_CAVE_3FV3
    
AlteringCave4F_MapBGEvents::

AlteringCave4F_MapEvents::
	map_events AlteringCave4F_EventObjects, AlteringCave4F_MapWarps, 0x0, AlteringCave4F_MapBGEvents
