Route125_Text_Lass1::
    .string "I came here because I want a\n"
    .string "Shell Bell, but...\p"
    .string "I don't want to go in there!\n"
    .string "It's all gross and wet!\p"
    .string "If you can get a Shell Bell...\n"
    .string "I'll trade this Focus Sash for it.$"

Route125_Text_Lass2::
    .string "I came here because I want a\n"
    .string "Shell Bell, but...\p"
    .string "I don't want to go in there!\n"
    .string "It's all gross and wet!\p"
    .string "Oh! You've got a Shell Bell!\n"
    .string "Please let me have it!\p"
    .string "I'll give you this Focus\n"
    .string "Sash for it! It's a good deal!$"

Route125_Text_Lass3::
    .string "Your Bag is too full...\n"
    .string "Wait, what?\p"
    .string "You seriously have two Shell\n"
    .string "Bells? C'mon, lighten the load!$"

Route125_Text_Lass4::
    .string "Oh, come on! Just my luck\n"
    .string "you'd be another bell nut...$"

Route125_Text_Lass5::
    .string "Thank you! Thank you thank\n"
    .string "you thank you so much!$"

Route125_Text_Lass6::
    .string "I like the Pokémon Chimecho.\p"
    .string "Isn't it a cutie holding this\n"
    .string "fashionable Shell Bell?$"

