SlateportCity_Text_164642:: @ 8164642
	.string "I'm the Energy Guru!\n"
	.string "I'll go for it and sell you what you need!$"

SlateportCity_Text_164682:: @ 8164682
	.string "Oh?\n"
	.string "Your {STR_VAR_1}...$"

SlateportCity_Text_164691:: @ 8164691
	.string "Went for it stupendously!\p"
	.string "As its reward, please give it this\n"
	.string "Effort Ribbon.$"

SlateportCity_Text_1646DD:: @ 81646DD
	.string "{PLAYER} received the Effort Ribbon.$"

SlateportCity_Text_1646FC:: @ 81646FC
	.string "{PLAYER} put the Effort Ribbon\n"
	.string "on {STR_VAR_1}.$"

SlateportCity_Text_16471C:: @ 816471C
	.string "You have to go for it a little harder.\p"
	.string "If you do, I'll give your Pokémon\n"
	.string "something nice.$"

SlateportCity_Text_164775:: @ 8164775
	.string "Oh! Your {STR_VAR_1}, that Effort\n"
	.string "Ribbon looks good on it!$"

SlateportCity_Text_1647A7:: @ 81647A7
	.string "The light of the lighthouse reaches\n"
	.string "dozens of miles away.\p"
	.string "I wonder if it doesn't startle Pokémon\n"
	.string "in the sea.$"

SlateportCity_Text_164814:: @ 8164814
	.string "Ooh, look at this!\p"
	.string "The seaweed you can get around these\n"
	.string "parts is fresh and full of life.\p"
	.string "Why, it looks like it can even rear up\n"
	.string "and attack!$"

SlateportCity_Text_1648A0:: @ 81648A0
	.string "Where the water is clean, the fruits\n"
	.string "of bountiful harvest gather.\p"
	.string "And where people gather, a market\n"
	.string "soon starts.\p"
	.string "That is how a town is born and grows.$"

SlateportCity_Text_164937:: @ 8164937
	.string "Shopping where you can breathe the\n"
	.string "scent of the ocean...\p"
	.string "Slateport is such a wonderful place!$"

SlateportCity_Text_164995:: @ 8164995
	.string "If you put Dolls or Cushions on the\n"
	.string "floor, they'll get dirty.\p"
	.string "I'm going to buy some Bricks so my\n"
	.string "Dolls and Cushions won't get dirty\l"
	.string "when I leave them out.$"

SlateportCity_Text_164A30:: @ 8164A30
	.string "Yeah! I've waited so long for this!\n"
	.string "Pokémon Contests!\l"
	.string "I'm going to enter!\p"
	.string "But before I do, I have to catch some\n"
	.string "Pokémon!$"

SlateportCity_Text_164AA9:: @ 8164AA9
	.string "Whew... I'm just bushed...\p"
	.string "I hiked over from Mauville City.\n"
	.string "But, boy, this city's huge.\p"
	.string "If I'd known this, I would've ridden\n"
	.string "my Bike here.$"

SlateportCity_Text_164B34:: @ 8164B34
	.string "Stern, the fellow who built the\n"
	.string "Museum, also happens to be the leader\l"
	.string "of an undersea exploration team.\p"
	.string "So, everyone calls him Capt. Stern.$"

SlateportCity_Text_164BBF:: @ 8164BBF
	.string "What is that over there?\n"
	.string "That long line...$"

SlateportCity_Text_164BEA:: @ 8164BEA
	.string "When I was a child, I visited the\n"
	.string "Museum often.\p"
	.string "I used to dream about the mysteries of\n"
	.string "the sea after seeing the exhibits.$"

SlateportCity_Text_164C64:: @ 8164C64
	.string "Hey, there! Quit pushing!\n"
	.string "This is the line, can't you see?$"

SlateportCity_Text_164C9F:: @ 8164C9F
	.string "Team Magma has a policy of\n"
	.string "assembling and dispersing at the\l"
	.string "operation site.$"

SlateportCity_Text_164CE8:: @ 8164CE8
	.string "Our Boss is brilliant.\p"
	.string "What would he want to do with a\n"
	.string "Museum now?$"

SlateportCity_Text_164D2B:: @ 8164D2B
	.string "What's the new scheme, I wonder?\p"
	.string "Our Boss is scary when he's mad, so\n"
	.string "I'd better not screw things up...$"

SlateportCity_Text_164D92:: @ 8164D92
	.string "If there's something we need in the\n"
	.string "Museum, we should take it all!$"

SlateportCity_Text_164DD5:: @ 8164DD5
	.string "Hey, you there!\n"
	.string "Don't butt in!$"

SlateportCity_Text_164DF4:: @ 8164DF4
	.string "A long line, huh?\p"
	.string "It reminds me of the times I lined up to\n"
	.string "buy smash-hit games...$"

SlateportCity_Text_164E46:: @ 8164E46
	.string "Why are we even lining up and paying?\n"
	.string "We should just march in!$"

SlateportCity_Text_164E85:: @ 8164E85
	.string "The sea is just so vast...\p"
	.string "Could the sea have been made by the\n"
	.string "tears shed by Pokémon?$"

SlateportCity_Text_164EDB:: @ 8164EDB
	.string "Do you know what they do with old\n"
	.string "ships that become too creaky to sail?\p"
	.string "They sink them in the sea so they\n"
	.string "become habitats for Pokémon.$"

SlateportCity_Text_164F62:: @ 8164F62
	.string "Whenever I visit here, I get carried\n"
	.string "away and buy too much.$"

SlateportCity_Text_164F9E:: @ 8164F9E
	.string "If you want to change your Pokémon's\n"
	.string "nickname, you'll have to get the Name\l"
	.string "Rater to help you.$"

SlateportCity_Text_164FFC:: @ 8164FFC
	.string "Any Pokémon you get in a trade, you\n"
	.string "can't change its nickname.\p"
	.string "The original Trainer's love for that\n"
	.string "Pokémon is in the nickname.$"

SlateportCity_Text_16507C:: @ 816507C
	.string "A Pokémon Contest Hall opened in\n"
	.string "Slateport recently.\p"
	.string "I plan on entering after I improve the\n"
	.string "condition of my Pokémon.$"

SlateportCity_Text_1650F1:: @ 81650F1
	.string "Do you know about the machine\n"
	.string "Berry Blender?$"

SlateportCity_Text_16511E:: @ 816511E
	.string "People have to work together to get it\n"
	.string "to spin faster.\p"
	.string "The faster you can make it spin, the\n"
	.string "better {POKEBLOCK}s you can get, I've heard.$"

SlateportCity_Text_1651A1:: @ 81651A1
	.string "It's used for making a kind of candy\n"
	.string "called a {POKEBLOCK}.\p"
	.string "If you give a good {POKEBLOCK} to a Pokémon,\n"
	.string "its condition will improve by a lot.$"

SlateportCity_Text_165222:: @ 8165222
	.string "I was hoping that it was a famous star\n"
	.string "so I could get an autograph.\p"
	.string "But who's that being interviewed?\n"
	.string "Isn't that Capt. Stern?$"

SlateportCity_Text_1652A0:: @ 81652A0
	.string "That lady interviewer is so cool and\n"
	.string "pretty.\p"
	.string "When I grow up, I'm going to be an\n"
	.string "international journalist!$"

SlateportCity_Text_16530A:: @ 816530A
	.string "Capt. Stern says they discovered\n"
	.string "something at the bottom of the sea.\p"
	.string "I wonder what it is?\n"
	.string "What could it be?$"

SlateportCity_Text_165376:: @ 8165376
	.string "What's going on here?\p"
	.string "Did the good Captain come back with\n"
	.string "a big fish from the ocean floor?$"

SlateportCity_Text_1653D1:: @ 81653D1
	.string "Hey! Are you watching?\n"
	.string "Am I on TV?$"

SlateportCity_Text_1653F4:: @ 81653F4
	.string "A TV interview! Here!\n"
	.string "The Captain's a celebrity!$"

SlateportCity_Text_165425:: @ 8165425
	.string "TY: Okay, Capt. Stern, a big smile\n"
	.string "for the camera!$"

SlateportCity_Text_165458:: @ 8165458
	.string "GABBY: I see, I see. You've had a most\n"
	.string "invaluable experience...$"

SlateportCity_Text_165498:: @ 8165498
	.string "CAPT. STERN: Yes, indeed. We intend to\n"
	.string "move ahead with our exploration.$"

SlateportCity_Text_1654E0:: @ 81654E0
	.string "GABBY: That's wonderful, Capt. Stern!\n"
	.string "Thank you for taking the time from\l"
	.string "your busy schedule to talk to us.\p"
	.string "We hope we can interview you again\n"
	.string "with news of more discoveries!$"

SlateportCity_Text_16558D:: @ 816558D
	.string "CAPT. STERN: Whew...\p"
	.string "That was my first time to be filmed for\n"
	.string "TV. That was nerve wracking.$"

SlateportCity_Text_1655E7:: @ 81655E7
	.string "Oh! {PLAYER}{KUN}!\n"
	.string "You're looking great!\p"
	.string "We made a huge discovery on our last\n"
	.string "seafloor exploration.\p"
	.string "We found an underwater cavern on\n"
	.string "Route 128.\p"
	.string "We think it's the habitat of a Pokémon\n"
	.string "that's said to have been long extinct.$"

SlateportCity_Text_1656BC:: @ 81656BC
	.string "Fufufu...\n"
	.string "Capt. Stern, I presume.\p"
	.string "We of Team Magma will assume\n"
	.string "control of your submarine!\p"
	.string "Your objections are meaningless!\n"
	.string "We expect your total cooperation!\p"
	.string "Fufufu...\n"
	.string "Just watch and learn what Team\l"
	.string "Magma has planned!$"

SlateportCity_Text_16578F:: @ 816578F
	.string "CAPT. STERN: What was that all about?\p"
	.string "It sounded like someone using a\n"
	.string "megaphone...\p"
	.string "Where did it come from?$"

SlateportCity_Text_1657FA:: @ 81657FA
	.string "It's from the Harbor!\p"
	.string "The submarine!\n"
	.string "They're trying to take it!$"

SlateportCity_Text_16583A:: @ 816583A
	.string "{PLAYER}{KUN}!\n"
	.string "Please, come with me!$"

SlateportCity_Text_165856:: @ 8165856
	.string "POKéMON CONTESTS\n"
	.string "HYPER RANK REGISTRATION\l"
	.string "“Let it burn! Pokémon Trainers!”$"

SlateportCity_Text_1658A0:: @ 81658A0
	.string "STERN'S SHIPYARD\p"
	.string "“Wanted: A sailor capable of sailing\n"
	.string "in all currents.”$"

SlateportCity_Text_1658E8:: @ 81658E8
	.string "STERN'S SHIPYARD\p"
	.string "“The ferry S.S. Tidal nears\n"
	.string "completion for serving the ports of\l"
	.string "Slateport and Lilycove.”$"

SlateportCity_Text_165952:: @ 8165952
	.string "STERN'S SHIPYARD\p"
	.string "“Boarding of the Slateport-Lilycove\n"
	.string "ferry S.S. Tidal is handled at the\l"
	.string "Harbor.”$"

SlateportCity_Text_1659B3:: @ 81659B3
	.string "POKéMON FAN CLUB\n"
	.string "“Calling all fans of Pokémon!”$"

SlateportCity_Text_1659E3:: @ 81659E3
	.string "“The endless sea sustains\n"
	.string "all life.”\p"
	.string "OCEANIC MUSEUM$"

SlateportCity_Text_165A17:: @ 8165A17
	.string "SLATEPORT CITY\p"
	.string "“The port where people and Pokémon\n"
	.string "cross paths.”$"

SlateportCity_Text_165A57:: @ 8165A57
	.string "SLATEPORT MARKET\n"
	.string "“Unique items found nowhere else!”$"

SlateportCity_Text_165A8B:: @ 8165A8B
	.string "SLATEPORT HARBOR\p"
	.string "“The ferry S.S. Tidal is under\n"
	.string "construction in the Shipyard.\p"
	.string "“Service is scheduled to begin\n"
	.string "shortly.”$"

SlateportCity_Text_165B02:: @ 8165B02
	.string "SLATEPORT HARBOR\p"
	.string "“Enjoy a delightful cruise on the\n"
	.string "ferry S.S. Tidal.”$"

SlateportCity_Text_165B48:: @ 8165B48
	.string "NAME RATER'S HOUSE\n"
	.string "Pokémon nicknames rated.”$"

SlateportCity_Text_BallsVendor::
	.string "Good day.\n"
	.string "I sell rare Balls from Johto.$"
