Route135_EventObjects::
	object_event 1, EVENT_OBJ_GFX_BREAKABLE_ROCK, 0, 11, 33, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, S_BreakableRock, FLAG_TEMP_11
	object_event 2, EVENT_OBJ_GFX_BREAKABLE_ROCK, 0, 12, 34, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, S_BreakableRock, FLAG_TEMP_12
	object_event 3, EVENT_OBJ_GFX_BREAKABLE_ROCK, 0, 13, 33, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, S_BreakableRock, FLAG_TEMP_13

Route135_MapEvents::
	map_events Route135_EventObjects, 0x0, 0x0, 0x0
