Route135_EventObjects::
	object_event 1, EVENT_OBJ_GFX_BREAKABLE_ROCK, 0, 11, 33, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, S_BreakableRock, FLAG_ROUTE_135_ROCK_1
	object_event 2, EVENT_OBJ_GFX_BREAKABLE_ROCK, 0, 12, 34, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, S_BreakableRock, FLAG_ROUTE_135_ROCK_2
	object_event 3, EVENT_OBJ_GFX_BREAKABLE_ROCK, 0, 13, 33, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, S_BreakableRock, FLAG_ROUTE_135_ROCK_3
    object_event 4, EVENT_OBJ_GFX_FISHERMAN, 0, 19, 40, 3, MOVEMENT_TYPE_FACE_RIGHT, 0, 0, 0, 0, Route135_EventScript_FishingGuy, 0
    object_event 5, EVENT_OBJ_GFX_ITEM_BALL, 0, 34, 39, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, Route135_EventScript_Item1, FLAG_ITEM_ROUTE135_0

Route135_MapEvents::
	map_events Route135_EventObjects, 0x0, 0x0, 0x0
