gAbilityDescription_Unimplemented:
	.string "Unimplemented$"

gAbilityDescription_None: @ 81F99CC
	.string "No special ability.$"

gAbilityDescription_Stench: @ 81F99E0
	.string "Helps repel wild Pokémon.\n"
    .string "No effect in battle.$"

gAbilityDescription_Drizzle: @ 81F99FA
	.string "Summons rain for 5 turns\n"
	.string "upon entering battle.$"

gAbilityDescription_SpeedBoost: @ 81F9A12
	.string "Raises Speed at the end\n"
	.string "of every turn.$"

gAbilityDescription_BattleArmor: @ 81F9A2A
gAbilityDescription_ShellArmor: @ 81FA0C6
	.string "Prevents critical hits.$"

gAbilityDescription_Sturdy: @ 81F9A40
	.string "Endures fainting at full\n"
	.string "HP, and blocks OHKOs.$"

gAbilityDescription_Damp: @ 81F9A5A
	.string "Prevents all combatants\n"
	.string "from self-destructing.$"

gAbilityDescription_Limber: @ 81F9A75
	.string "Prevents paralysis.$"

gAbilityDescription_SandVeil: @ 81F9A89
	.string "20% chance to avoid\n"
	.string "moves in a sandstorm.$"
gAbilityDescription_SnowCloak:
	.string "20% chance to avoid\n"
	.string "moves in a hailstorm.$"

gAbilityDescription_Static: @ 81F9AA5
	.string "30% chance to paralyze\n"
	.string "a foe that makes contact.$"

gAbilityDescription_VoltAbsorb: @ 81F9ABB
	.string "Absorbs Electric moves to\n"
	.string "restore 25% HP.$"

gAbilityDescription_WaterAbsorb: @ 81F9AD6
	.string "Absorbs Water moves to\n"
	.string "restore 25% HP.$"

gAbilityDescription_Oblivious: @ 81F9AED
	.string "Prevents infatuation.$"

gAbilityDescription_CloudNine: @ 81F9B02
gAbilityDescription_AirLock: @ 81FA0F6
	.string "Suspends the effects of\n"
	.string "weather while on the field.$"

gAbilityDescription_CompoundEyes: @ 81F9B1B
	.string "Raises accuracy by 30% of\n"
	.string "the move's base accuracy.$"

gAbilityDescription_Insomnia: @ 81F9B2C
gAbilityDescription_VitalSpirit: @ 81FA08B
	.string "Prevents sleep.$"

gAbilityDescription_ColorChange: @ 81F9B3C
	.string "Changes type to the type\n"
	.string "of moves used on it.$"
gAbilityDescription_Protean:
	.string "Changes type to match\n"
    .string "the type of own move.$"

gAbilityDescription_Immunity: @ 81F9B58
	.string "Prevents poisoning.$"

gAbilityDescription_FlashFire: @ 81F9B6C
	.string "Absorbs Fire moves to\n"
	.string "boost Fire power by 50%.$"

gAbilityDescription_ShieldDust: @ 81F9B86
	.string "Blocks additional effects\n"
	.string "from incoming moves.$"

gAbilityDescription_OwnTempo: @ 81F9B9E
	.string "Prevents confusion.$"

gAbilityDescription_SuctionCups: @ 81F9BB2
	.string "Firmly anchors the body,\n"
	.string "negating forced switches.$"

gAbilityDescription_Intimidate: @ 81F9BCB
	.string "Lowers the foe's Attack\n"
	.string "upon entering battle.$"

gAbilityDescription_ShadowTag: @ 81F9BE4
	.string "Prevents the foe from\n"
    .string "escaping.$"

gAbilityDescription_RoughSkin: @ 81F9BFF
	.string "Inflicts damage on a foe\n"
	.string "that makes contact.$"

gAbilityDescription_WonderGuard: @ 81F9C0F
	.string "Avoids damaging moves that\n"
    .string "are not supereffective.$"

gAbilityDescription_Levitate: @ 81F9C27
	.string "Gives immunity to Ground\n"
    .string "moves and Spikes.$"

gAbilityDescription_EffectSpore: @ 81F9C42
	.string "30% to poison, sleep,\n"
	.string "or paralyze on contact.$"

gAbilityDescription_Synchronize: @ 81F9C5C
	.string "Passes a burn, poison, or\n"
	.string "paralysis to inflicting foe.$"

gAbilityDescription_ClearBody: @ 81F9C77
gAbilityDescription_WhiteSmoke: @ 81FA09B
	.string "Prevents others from\n"
    .string "lowering its stats.$"

gAbilityDescription_NaturalCure: @ 81F9C93
	.string "Heals from status\n"
	.string "when switching out.$"
gAbilityDescription_Regenerator:
	.string "Regains 33% HP\n"
	.string "when switching out.$"

gAbilityDescription_LightningRod: @ 81F9CAD
	.string "Draws and absorbs Electric\n"
	.string "moves to boost Sp. Atk.$"

gAbilityDescription_SereneGrace: @ 81F9CC5
	.string "Doubles the chance of\n"
    .string "added effects occurring.$"

gAbilityDescription_SwiftSwim: @ 81F9CDD
	.string "Doubles Speed in rain.$"
gAbilityDescription_Chlorophyll: @ 81F9CF3
	.string "Doubles Speed in sunshine.$"
gAbilityDescription_SandRush:
	.string "Doubles Speed in sandstorms.$"

gAbilityDescription_Illuminate: @ 81F9D0D
	.string "Encounter rate increases.\n"
    .string "No effect in battle.$"

gAbilityDescription_Trace: @ 81F9D27
	.string "Copies a foe's Ability.$"

gAbilityDescription_HugePower: @ 81F9D3F
gAbilityDescription_PurePower: @ 81FA0B7
	.string "Doubles Attack.$"
gAbilityDescription_FurCoat:
	.string "Doubles Defense.$"

gAbilityDescription_PoisonPoint: @ 81F9D4E
	.string "30% chance to poison a\n"
	.string "foe that makes contact.$"

gAbilityDescription_InnerFocus: @ 81F9D66
	.string "Prevents flinching.$"

gAbilityDescription_MagmaArmor: @ 81F9D7A
	.string "Prevents freezing.$"

gAbilityDescription_WaterVeil: @ 81F9D8D
	.string "Prevents burns.$"

gAbilityDescription_MagnetPull: @ 81F9D9D
	.string "Prevents Steel-type foes\n"
    .string "from escaping.$"

gAbilityDescription_Soundproof: @ 81F9DB7
	.string "Gives immunity to sound-\n"
    .string "based moves.$"

gAbilityDescription_RainDish: @ 81F9DD1
	.string "Recovers 1/16 max HP at\n"
	.string "end of turn in rain.$"
gAbilityDescription_IceBody:
	.string "Recovers 1/16 max HP at\n"
	.string "end of turn in hail.$"

gAbilityDescription_SandStream: @ 81F9DED
	.string "Summons a sandstorm for 5\n"
	.string "turns upon entering battle.$"

gAbilityDescription_Pressure: @ 81F9E02
	.string "Raises the foe's PP usage.$"

gAbilityDescription_ThickFat: @ 81F9E19
	.string "Halves damage taken from\n"
    .string "Fire and Ice moves.$"

gAbilityDescription_EarlyBird: @ 81F9E33
	.string "Awakens from sleep twice\n"
    .string "as fast as normally.$"

gAbilityDescription_FlameBody: @ 81F9E4F
	.string "30% chance to burn a\n"
	.string "foe that makes contact.$"

gAbilityDescription_RunAway: @ 81F9E69
	.string "Enables a sure getaway\n"
    .string "from wild Pokémon.$"

gAbilityDescription_KeenEye: @ 81F9E80
	.string "Prevents others from\n"
    .string "lowering its accuracy.$"

gAbilityDescription_HyperCutter: @ 81F9E9B
	.string "Prevents others from\n"
    .string "lowering its Attack.$"
gAbilityDescription_BigPecks:
	.string "Prevents others from\n"
    .string "lowering its Defense.$"

gAbilityDescription_Pickup: @ 81F9EB6
	.string "May pick up items.$"

gAbilityDescription_Truant: @ 81F9EC9
	.string "Slacks off instead of\n"
	.string "moving every other turn.$"

gAbilityDescription_Hustle: @ 81F9EE5
	.string "Physical moves are 50%\n"
    .string "stronger but 80% accurate.$"

gAbilityDescription_CuteCharm: @ 81F9F00
	.string "30% chance to infatuate\n"
	.string "a foe that makes contact.$"

gAbilityDescription_Plus: @ 81F9F17
	.string "Boosts Sp. Atk by 50% if\n"
    .string "another Pokémon has Minus.$"

gAbilityDescription_Minus: @ 81F9F2D
	.string "Boosts Sp. Atk by 50% if\n"
    .string "another Pokémon has Plus.$"

gAbilityDescription_Forecast: @ 81F9F42
	.string "Transforms to Fire, Water,\n"
    .string "or Ice with the weather.$"

gAbilityDescription_StickyHold: @ 81F9F5C
	.string "Prevents held item theft\n"
    .string "and destruction.$"

gAbilityDescription_ShedSkin: @ 81F9F71
	.string "1/3 chance to shed status\n"
    .string "at end of turn.$"

gAbilityDescription_Guts: @ 81F9F8D
	.string "+50% Attack when suffering\n"
    .string "from status.$"
gAbilityDescription_ToxicBoost:
	.string "+50% Attack when suffering\n"
    .string "from poison.$"
gAbilityDescription_MarvelScale: @ 81F9FA6
	.string "+50% Defense when\n"
    .string "suffering from status.$"
gAbilityDescription_QuickFeet:
	.string "+50% Speed when suffering\n"
    .string "from status.$"

gAbilityDescription_LiquidOoze: @ 81F9FC0
	.string "Harms attackers using\n"
	.string "draining moves.$"

gAbilityDescription_Overgrow: @ 81F9FD8
    .string "While at 1/3 HP or less,\n"
	.string "boosts Grass moves by 50%.$"

gAbilityDescription_Blaze: @ 81F9FF4
    .string "While at 1/3 HP or less,\n"
	.string "boosts Fire moves by 50%.$"

gAbilityDescription_Torrent: @ 81FA00F
    .string "While at 1/3 HP or less,\n"
	.string "boosts Water moves by 50%.$"

gAbilityDescription_Swarm: @ 81FA02B
    .string "While at 1/3 HP or less,\n"
	.string "boosts Bug moves by 50%.$"

gAbilityDescription_RockHead: @ 81FA045
	.string "Protects from recoil\n"
    .string "damage (except Struggle).$"

gAbilityDescription_Drought: @ 81FA05D
	.string "Summons sunlight for 5\n"
	.string "turns upon entering battle.$"

gAbilityDescription_ArenaTrap: @ 81FA079
	.string "Prevents grounded foes\n"
    .string "from escaping.$"

gAbilityDescription_Gluttony:
	.string "Eats some kinds of berries\n"
    .string "at 50% HP instead of 25%.$"

gAbilityDescription_Hydration:
	.string "Heals status at end of\n"
    .string "turn in rain.$"

gAbilityDescription_PoisonHeal:
	.string "While poisoned, regains 1/8\n"
    .string "HP instead of losing any.$"

gAbilityDescription_Stall:
	.string "All moves have negative\n"
    .string "priority.$"

gAbilityDescription_NoGuard:
	.string "Ensures all moves used\n"
    .string "and taken do not miss.$"

gAbilityDescription_TintedLens:
	.string "Doubles the power of\n"
    .string "not very effective moves.$"

gAbilityDescription_SolidRock:
gAbilityDescription_Filter:
	.string "Takes 1/4 less damage from\n"
    .string "supereffective moves.$"

gAbilityDescription_TangledFeet:
	.string "50% chance to avoid\n"
    .string "moves while confused.$"

gAbilityDescription_Anticipation:
	.string "Senses foe's OHKO moves\n"
    .string "and supereffective moves.$"

gAbilityDescription_Frisk:
    .string "Checks the foe's hold\n"
    .string "items on entry.$"

gAbilityDescription_SolarPower:
    .string "+50% Sp. Atk in sunlight,\n"
    .string "but loses HP each turn.$"

gAbilityDescription_SuperLuck:
    .string "Lands critical hits more\n"
    .string "often.$"

gAbilityDescription_MoldBreaker:
    .string "Bypasses foe's Abilities\n"
    .string "that would block moves.$"

gAbilityDescription_Sniper:
	.string "+50% power to moves that\n"
    .string "land critical hits.$"

gAbilityDescription_Unnerve:
	.string "Prevents foes from\n"
    .string "using berries.$"

gAbilityDescription_Rivalry:
	.string "+25% power vs. same gender.\n"
    .string "-25% power vs. opposite.$"

gAbilityDescription_SheerForce:
	.string "Added effects won't occur,\n"
    .string "but boost power by 30%.$"

gAbilityDescription_MagicGuard:
	.string "Blocks all damage\n"
    .string "except for moves.$"

gAbilityDescription_Unaware:
	.string "Ignores stat changes\n"
    .string "of other Pokémon.$"

gAbilityDescription_FriendGuard:
	.string "Reduces damage done to\n"
    .string "allies by 25%.$"

gAbilityDescription_DrySkin:
	.string "Absorbs water (and rain),\n"
    .string "but vulnerable to heat.$"

gAbilityDescription_WonderSkin:
	.string "50% chance to avoid\n"
    .string "status moves.$"

gAbilityDescription_SandForce:
	.string "+30% power to earthen\n"
    .string "moves during sandstorms.$"

gAbilityDescription_Technician:
    .string "+50% power on moves\n"
    .string "with 60 power or less.$"

gAbilityDescription_AngerPoint:
    .string "Maxes Attack if hit\n"
    .string "with a critical hit.$"

gAbilityDescription_Justified:
    .string "Raises Attack if hit\n"
    .string "with a Dark attack.$"

gAbilityDescription_Steadfast:
	.string "Raises Speed when\n"
    .string "flinching.$"

gAbilityDescription_Analytic:
    .string "+30% power when moving\n"
    .string "after the target.$"

gAbilityDescription_PoisonTouch:
    .string "30% chance to poison\n"
    .string "when causing contact.$"

gAbilityDescription_SkillLink:
    .string "Multi-hit moves hit as\n"
    .string "many times as possible.$"

gAbilityDescription_Overcoat:
    .string "Protects against powder\n"
    .string "and weather damage.$"

gAbilityDescription_CursedBody:
	.string "30% chance to disable\n"
    .string "moves that cause damage.$"

gAbilityDescription_Forewarn:
	.string "Senses the foe's\n"
    .string "strongest move.$"

gAbilityDescription_WeakArmor:
	.string "Physical hits shed\n"
    .string "Defense for Speed.$"

gAbilityDescription_Aftermath:
	.string "Inflicts damage when\n"
	.string "fainting by contact.$"

gAbilityDescription_Harvest:
	.string "May recycle berries\n"
	.string "at end of turn.$"

gAbilityDescription_Reckless:
	.string "+20% power on moves\n"
    .string "that cause recoil.$"

gAbilityDescription_IronFist:
	.string "+20% power on punching\n"
    .string "moves.$"

gAbilityDescription_StrongJaw:
	.string "+50% power on biting\n"
    .string "moves.$"

gAbilityDescription_Unburden:
	.string "Doubles Speed after\n"
    .string "losing held item.$"

gAbilityDescription_Healer:
	.string "30% chance to cure\n"
    .string "ally's status.$"

gAbilityDescription_Scrappy:
	.string "Ignores the immunities\n"
    .string "of the Ghost type.$"

gAbilityDescription_Moxie:
	.string "Raises Attack when\n"
    .string "defeating a Pokémon.$"

gAbilityDescription_Imposter:
	.string "Transforms into the\n"
    .string "foe on entry.$"

gAbilityDescription_Adaptability:
	.string "+33% power on moves\n"
    .string "of the same type.$"

gAbilityDescription_Download:
    .string "Raises Attack or Sp. Atk\n"
    .string "depending on foe's stats.$"

gAbilityDescription_Rattled:
    .string "Boosts Speed when hit\n"
    .string "by Dark, Ghost, or Bug move.$"

gAbilityDescription_Multiscale:
	.string "Takes half damage when\n"
    .string "at full HP.$"

gAbilityDescription_MagicBounce:
    .string "Reflects incoming status\n"
    .string "moves back at the user.$"

gAbilityDescription_SapSipper:
	.string "Absorbs Grass moves to\n"
    .string "boost Attack.$"

gAbilityDescription_Prankster:
	.string "Status moves gain\n"
    .string "+1 priority.$"
gAbilityDescription_Triage:
	.string "Healing moves gain\n"
    .string "+3 priority.$"

gAbilityDescription_Telepathy:
    .string "Anticipates moves from\n"
	.string "allies and avoids them.$"

gAbilityDescription_Contrary:
	.string "Makes stat changes have\n"
    .string "the opposite effect.$"

gAbilityDescription_Moody:
	.string "Raises and lowers stats\n"
    .string "randomly every turn.$"

gAbilityDescription_LightMetal:
	.string "Halves weight.$"

gAbilityDescription_HeavyMetal:
	.string "Doubles weight.$"

gAbilityDescription_StormDrain:
	.string "Draws and absorbs Water\n"
	.string "moves to boost Sp. Atk.$"

gAbilityDescription_Infiltrator:
	.string "Bypasses substitutes and\n"
    .string "and protective barriers.$"

gAbilityDescription_Defiant:
    .string "Sharply raises Attack when\n"
    .string "stats are lowered.$"

gAbilityDescription_Competitive:
    .string "Sharply raises Sp. Atk when\n"
    .string "stats are lowered.$"

gAbilityDescription_Merciless:
    .string "Always lands critical hits\n"
    .string "against poisoned foes.$"

gAbilityDescription_GaleWings:
    .string "When at full HP, Flying\n"
    .string "moves gain +1 priority.$"

	.align 2
gAbilityDescriptions:: @ 81FA110
	.4byte gAbilityDescription_None
	.4byte gAbilityDescription_Stench
	.4byte gAbilityDescription_Drizzle
	.4byte gAbilityDescription_SpeedBoost
	.4byte gAbilityDescription_BattleArmor
	.4byte gAbilityDescription_Sturdy
	.4byte gAbilityDescription_Damp
	.4byte gAbilityDescription_Limber
	.4byte gAbilityDescription_SandVeil
	.4byte gAbilityDescription_Static
	.4byte gAbilityDescription_VoltAbsorb
	.4byte gAbilityDescription_WaterAbsorb
	.4byte gAbilityDescription_Oblivious
	.4byte gAbilityDescription_CloudNine
	.4byte gAbilityDescription_CompoundEyes
	.4byte gAbilityDescription_Insomnia
	.4byte gAbilityDescription_ColorChange
	.4byte gAbilityDescription_Immunity
	.4byte gAbilityDescription_FlashFire
	.4byte gAbilityDescription_ShieldDust
	.4byte gAbilityDescription_OwnTempo
	.4byte gAbilityDescription_SuctionCups
	.4byte gAbilityDescription_Intimidate
	.4byte gAbilityDescription_ShadowTag
	.4byte gAbilityDescription_RoughSkin
	.4byte gAbilityDescription_WonderGuard
	.4byte gAbilityDescription_Levitate
	.4byte gAbilityDescription_EffectSpore
	.4byte gAbilityDescription_Synchronize
	.4byte gAbilityDescription_ClearBody
	.4byte gAbilityDescription_NaturalCure
	.4byte gAbilityDescription_LightningRod
	.4byte gAbilityDescription_SereneGrace
	.4byte gAbilityDescription_SwiftSwim
	.4byte gAbilityDescription_Chlorophyll
	.4byte gAbilityDescription_Illuminate
	.4byte gAbilityDescription_Trace
	.4byte gAbilityDescription_HugePower
	.4byte gAbilityDescription_PoisonPoint
	.4byte gAbilityDescription_InnerFocus
	.4byte gAbilityDescription_MagmaArmor
	.4byte gAbilityDescription_WaterVeil
	.4byte gAbilityDescription_MagnetPull
	.4byte gAbilityDescription_Soundproof
	.4byte gAbilityDescription_RainDish
	.4byte gAbilityDescription_SandStream
	.4byte gAbilityDescription_Pressure
	.4byte gAbilityDescription_ThickFat
	.4byte gAbilityDescription_EarlyBird
	.4byte gAbilityDescription_FlameBody
	.4byte gAbilityDescription_RunAway
	.4byte gAbilityDescription_KeenEye
	.4byte gAbilityDescription_HyperCutter
	.4byte gAbilityDescription_Pickup
	.4byte gAbilityDescription_Truant
	.4byte gAbilityDescription_Hustle
	.4byte gAbilityDescription_CuteCharm
	.4byte gAbilityDescription_Plus
	.4byte gAbilityDescription_Minus
	.4byte gAbilityDescription_Forecast
	.4byte gAbilityDescription_StickyHold
	.4byte gAbilityDescription_ShedSkin
	.4byte gAbilityDescription_Guts
	.4byte gAbilityDescription_MarvelScale
	.4byte gAbilityDescription_LiquidOoze
	.4byte gAbilityDescription_Overgrow
	.4byte gAbilityDescription_Blaze
	.4byte gAbilityDescription_Torrent
	.4byte gAbilityDescription_Swarm
	.4byte gAbilityDescription_RockHead
	.4byte gAbilityDescription_Drought
	.4byte gAbilityDescription_ArenaTrap
	.4byte gAbilityDescription_VitalSpirit
	.4byte gAbilityDescription_WhiteSmoke
	.4byte gAbilityDescription_PurePower
	.4byte gAbilityDescription_ShellArmor
	.4byte gAbilityDescription_Unimplemented
	.4byte gAbilityDescription_AirLock
	.4byte gAbilityDescription_QuickFeet
	.4byte gAbilityDescription_Gluttony
	.4byte gAbilityDescription_Hydration
	.4byte gAbilityDescription_PoisonHeal
	.4byte gAbilityDescription_Stall
	.4byte gAbilityDescription_NoGuard
	.4byte gAbilityDescription_TintedLens
	.4byte gAbilityDescription_SolidRock
	.4byte gAbilityDescription_TangledFeet
	.4byte gAbilityDescription_Anticipation
	.4byte gAbilityDescription_Frisk
	.4byte gAbilityDescription_SolarPower
	.4byte gAbilityDescription_SuperLuck
	.4byte gAbilityDescription_MoldBreaker
	.4byte gAbilityDescription_IceBody
	.4byte gAbilityDescription_Sniper
	.4byte gAbilityDescription_BigPecks
	.4byte gAbilityDescription_Unnerve
	.4byte gAbilityDescription_SandRush
	.4byte gAbilityDescription_Rivalry
	.4byte gAbilityDescription_SheerForce
	.4byte gAbilityDescription_MagicGuard
	.4byte gAbilityDescription_Unaware
	.4byte gAbilityDescription_FriendGuard
	.4byte gAbilityDescription_Competitive
	.4byte gAbilityDescription_Infiltrator
	.4byte gAbilityDescription_DrySkin
	.4byte gAbilityDescription_WonderSkin
	.4byte gAbilityDescription_SandForce
	.4byte gAbilityDescription_Technician
	.4byte gAbilityDescription_AngerPoint
	.4byte gAbilityDescription_Defiant
	.4byte gAbilityDescription_Regenerator
	.4byte gAbilityDescription_Justified
	.4byte gAbilityDescription_Steadfast
	.4byte gAbilityDescription_Analytic
	.4byte gAbilityDescription_PoisonTouch
	.4byte gAbilityDescription_SkillLink
	.4byte gAbilityDescription_Overcoat
	.4byte gAbilityDescription_CursedBody
	.4byte gAbilityDescription_Forewarn
	.4byte gAbilityDescription_WeakArmor
	.4byte gAbilityDescription_Aftermath
	.4byte gAbilityDescription_Harvest
	.4byte gAbilityDescription_Reckless
	.4byte gAbilityDescription_IronFist
	.4byte gAbilityDescription_Unburden
	.4byte gAbilityDescription_Healer
	.4byte gAbilityDescription_Unimplemented
	.4byte gAbilityDescription_Scrappy
	.4byte gAbilityDescription_Filter
	.4byte gAbilityDescription_Moxie
	.4byte gAbilityDescription_Imposter
	.4byte gAbilityDescription_Adaptability
	.4byte gAbilityDescription_Download
	.4byte gAbilityDescription_Rattled
	.4byte gAbilityDescription_SnowCloak
	.4byte gAbilityDescription_Multiscale
	.4byte gAbilityDescription_MagicBounce
	.4byte gAbilityDescription_SapSipper
	.4byte gAbilityDescription_Prankster
	.4byte gAbilityDescription_Telepathy
	.4byte gAbilityDescription_Contrary
	.4byte gAbilityDescription_Unimplemented
	.4byte gAbilityDescription_Unimplemented
	.4byte gAbilityDescription_Moody
	.4byte gAbilityDescription_LightMetal
	.4byte gAbilityDescription_Protean
	.4byte gAbilityDescription_ToxicBoost
	.4byte gAbilityDescription_HeavyMetal
	.4byte gAbilityDescription_StormDrain
	.4byte gAbilityDescription_Unimplemented
	.4byte gAbilityDescription_Unimplemented
    .4byte gAbilityDescription_FurCoat
    .4byte gAbilityDescription_RoughSkin
    .4byte gAbilityDescription_Triage
    .4byte gAbilityDescription_StrongJaw
    .4byte gAbilityDescription_Merciless
    .4byte gAbilityDescription_GaleWings
