gAbilityNames:: @ 81FA248
	.string "-------$", 13
	.string "Stench$", 13
	.string "Drizzle$", 13
	.string "Speed Boost$", 13
	.string "Battle Armor$", 13
	.string "Sturdy$", 13
	.string "Damp$", 13
	.string "Limber$", 13
	.string "Sand Veil$", 13
	.string "Static$", 13
	.string "Volt Absorb$", 13
	.string "Water Absorb$", 13
	.string "Oblivious$", 13
	.string "Cloud Nine$", 13
	.string "CompoundEyes$", 13
	.string "Insomnia$", 13
	.string "Color Change$", 13
	.string "Immunity$", 13
	.string "Flash Fire$", 13
	.string "Shield Dust$", 13
	.string "Own Tempo$", 13
	.string "Suction Cups$", 13
	.string "Intimidate$", 13
	.string "Shadow Tag$", 13
	.string "Rough Skin$", 13
	.string "Wonder Guard$", 13
	.string "Levitate$", 13
	.string "Effect Spore$", 13
	.string "Synchronize$", 13
	.string "Clear Body$", 13
	.string "Natural Cure$", 13
	.string "LightningRod$", 13
	.string "Serene Grace$", 13
	.string "Swift Swim$", 13
	.string "Chlorophyll$", 13
	.string "Illuminate$", 13
	.string "Trace$", 13
	.string "Huge Power$", 13
	.string "Poison Point$", 13
	.string "Inner Focus$", 13
	.string "Magma Armor$", 13
	.string "Water Veil$", 13
	.string "Magnet Pull$", 13
	.string "Soundproof$", 13
	.string "Rain Dish$", 13
	.string "Sand Stream$", 13
	.string "Pressure$", 13
	.string "Thick Fat$", 13
	.string "Early Bird$", 13
	.string "Flame Body$", 13
	.string "Run Away$", 13
	.string "Keen Eye$", 13
	.string "Hyper Cutter$", 13
	.string "Pickup$", 13
	.string "Truant$", 13
	.string "Hustle$", 13
	.string "Cute Charm$", 13
	.string "Plus$", 13
	.string "Minus$", 13
	.string "Forecast$", 13
	.string "Sticky Hold$", 13
	.string "Shed Skin$", 13
	.string "Guts$", 13
	.string "Marvel Scale$", 13
	.string "Liquid Ooze$", 13
	.string "Overgrow$", 13
	.string "Blaze$", 13
	.string "Torrent$", 13
	.string "Swarm$", 13
	.string "Rock Head$", 13
	.string "Drought$", 13
	.string "Arena Trap$", 13
	.string "Vital Spirit$", 13
	.string "White Smoke$", 13
	.string "Pure Power$", 13
	.string "Shell Armor$", 13
	.string "CACOPHONY$", 13
	.string "Air Lock$", 13
	.string "Quick Feet$", 13
	.string "Gluttony$", 13
	.string "Hydration$", 13
	.string "Poison Heal$", 13
	.string "Stall$", 13
	.string "No Guard$", 13
	.string "Tinted Lens$", 13
	.string "Solid Rock$", 13
	.string "Tangled Feet$", 13
	.string "Anticipation$", 13
	.string "Frisk$", 13
	.string "Solar Power$", 13
	.string "Super Luck$", 13
	.string "Mold Breaker$", 13
	.string "Ice Body$", 13
	.string "Sniper$", 13
	.string "Big Pecks$", 13
	.string "Unnerve$", 13
	.string "Sand Rush$", 13
	.string "Rivalry$", 13
	.string "Sheer Force$", 13
	.string "Magic Guard$", 13
	.string "Unaware$", 13
	.string "Friend Guard$", 13
	.string "COMPETITIVE$", 13
	.string "INFILTRATOR$", 13
	.string "Dry Skin$", 13
	.string "Wonder Skin$", 13
	.string "Sand Force$", 13
	.string "Technician$", 13
	.string "Anger Point$", 13
	.string "DEFIANT$", 13
	.string "Regenerator$", 13
	.string "Justified$", 13
	.string "Steadfast$", 13
	.string "Analytic$", 13
	.string "Poison Touch$", 13
	.string "Skill Link$", 13
	.string "Overcoat$", 13
	.string "Cursed Body$", 13
	.string "Forewarn$", 13
	.string "Weak Armor$", 13
	.string "Aftermath$", 13
	.string "Harvest$", 13
	.string "Reckless$", 13
	.string "Iron Fist$", 13
	.string "Unburden$", 13
	.string "Healer$", 13
	.string "LEAF GUARD$", 13
	.string "Scrappy$", 13
	.string "Filter$", 13
	.string "Moxie$", 13
	.string "Imposter$", 13
	.string "Adaptability$", 13
	.string "Download$", 13
	.string "Rattled$", 13
	.string "Snow Cloak$", 13
	.string "Multiscale$", 13
	.string "Magic Bounce$", 13
	.string "Sap Sipper$", 13
	.string "PRANKSTER$", 13
	.string "TELEPATHY$", 13
	.string "CONTRARY$", 13
	.string "PICKPOCKET$", 13
	.string "HONEY GATHER$", 13
	.string "MOODY$", 13
	.string "LIGHT METAL$", 13
	.string "PROTEAN$", 13
	.string "TOXIC BOOST$", 13
	.string "HEAVY METAL$", 13
	.string "STORM DRAIN$", 13

