EverGrandeCity_HallOfFame_Text_191841:: @ 8191841
	.string "STEVEN: This room...\p"
	.string "This is where we keep records of\n"
	.string "Pokémon that prevailed through\l"
	.string "harsh battles.\p"
	.string "It is here that the League Champions\n"
	.string "are honored.$"

EverGrandeCity_HallOfFame_Text_1918D7:: @ 81918D7
	.string "STEVEN: Come on, let's record your\n"
	.string "name as a Trainer who triumphed over\l"
	.string "the Pokémon League, and the names of\l"
	.string "the partners who battled with you.$"
