MauvilleCity_GameCorner_Text_181C35:: @ 8181C35
	.string "This is Mauville Game Corner.$"

MauvilleCity_GameCorner_Text_181C53:: @ 8181C53
	.string "Okay, you wanted some Coins for\n"
	.string "the games?\p"
	.string "But you don't have a Coin Case for\n"
	.string "stowing the Coins.$"

MauvilleCity_GameCorner_Text_181CB4:: @ 8181CB4
	.string "Were you looking for Coins?\p"
	.string "It's ¥1000 for 50 Coins.\n"
	.string "Would you like some?$"

MauvilleCity_GameCorner_Text_181CFE:: @ 8181CFE
	.string "Thank you very much!\n"
	.string "Here are your Coins!$"

MauvilleCity_GameCorner_Text_181D28:: @ 8181D28
	.string "Um... You don't appear to have\n"
	.string "enough money...$"

MauvilleCity_GameCorner_Text_181D57:: @ 8181D57
	.string "Oh?\n"
	.string "Your Coin Case is full.$"

MauvilleCity_GameCorner_Text_181D73:: @ 8181D73
	.string "Oh... You don't need Coins, then?\n"
	.string "Good luck on your adventure!$"

UnknownString_8181DB2: @ 8181DB2
	.string "It's ¥1,000 for 50 Coins.\n"
	.string "Would you like some?$"

MauvilleCity_GameCorner_Text_181DE1:: @ 8181DE1
	.string "Welcome.\p"
	.string "You can exchange your Coins for\n"
	.string "prizes here.$"

MauvilleCity_GameCorner_Text_181E17:: @ 8181E17
	.string "Which prize would you like?$"

MauvilleCity_GameCorner_Text_181E33:: @ 8181E33
	.string "So your choice is {STR_VAR_1}?$"

MauvilleCity_GameCorner_Text_181E49:: @ 8181E49
	.string "Thank you!\n"
	.string "We'll send it to your PC at home.$"

MauvilleCity_GameCorner_Text_181E76:: @ 8181E76
	.string "You don't have enough Coins.$"

UnknownString_8181E93: @ 8181E93
	.string "There isn't any room available for\n"
	.string "placing {STR_VAR_1}.$"

MauvilleCity_GameCorner_Text_181EC2:: @ 8181EC2
	.string "Oh, is that so? \n"
	.string "You need to save some Coins before\l"
	.string "coming back here.$"

MauvilleCity_GameCorner_Text_181F08:: @ 8181F08
	.string "Here you go!$"

UnknownString_8181F15: @ 8181F15
	.string "Oh, you can't carry any more than that.$"

MauvilleCity_GameCorner_Text_181F3D:: @ 8181F3D
	.string "I made a mistake and got two of the\n"
	.string "same Dolls.\p"
	.string "Would you like one of them?$"

MauvilleCity_GameCorner_Text_181F89:: @ 8181F89
	.string "There you go!$"

MauvilleCity_GameCorner_Text_181F97:: @ 8181F97
	.string "Huh?\n"
	.string "You want it, but not right now?$"

MauvilleCity_GameCorner_Text_181FBC:: @ 8181FBC
	.string "Oh, don't be so negative!\n"
	.string "You can have this!$"

MauvilleCity_GameCorner_Text_181FE9:: @ 8181FE9
	.string "There's a prize I want, but I can't win\n"
	.string "the jackpot.$"

MauvilleCity_GameCorner_Text_18201E:: @ 818201E
	.string "Hey, kid, if you want to play here,\n"
	.string "you need a Coin Case.\p"
	.string "I think the young lady next door\n"
	.string "had one. Go see her!$"

MauvilleCity_GameCorner_Text_18208E:: @ 818208E
	.string "My luck can only last so long.\n"
	.string "This is too much for me.\l"
	.string "Here, take some Coins!$"

MauvilleCity_GameCorner_Text_1820DD:: @ 81820DD
	.string "Mauville has something for\n"
	.string "everyone.\p"
	.string "For me, it's the Game Corner.$"

MauvilleCity_GameCorner_Text_182120:: @ 8182120
	.string "The Roulette tables have different\n"
	.string "rates.\p"
	.string "Check your Coins if you're going to\n"
	.string "pick a table.$"

MauvilleCity_GameCorner_Text_18217C:: @ 818217C
	.string "It's easy to lose track of time in here. \n"
	.string "I should get back to work.$"

MauvilleCity_GameCorner_Text_1821C1:: @ 81821C1
	.string "Coins are needed to play here in the\n"
	.string "Game Corner.$"

MauvilleCity_GameCorner_Text_1821F3:: @ 81821F3
	.string "This Roulette thing...\n"
	.string "It's rather demanding.\p"
	.string "Win or lose, it's only by luck.$"

MauvilleCity_GameCorner_Text_182241:: @ 8182241
	.string "Up to three Coins can be used to play\n"
	.string "the slots.$"

MauvilleCity_GameCorner_Text_182272:: @ 8182272
	.string "It's very difficult to make it stop\n"
	.string "right on “7.”\p"
	.string "If it stops on “7” during the Reel Time\n"
	.string "bonus game, you'll receive extra Coins.$"

MauvilleCity_GameCorner_Text_1822F4:: @ 81822F4
	.string "Here's some information for you\n"
	.string "about the slots.\p"
	.string "The more lightning bolts you stock, the\n"
	.string "more Reel Time chances you get.\p"
	.string "In a game with the maximum five Reel\n"
	.string "Time chances...\p"
	.string "It is possible to receive four regular\n"
	.string "bonuses, then a big bonus.\p"
	.string "The big bonus is 660 Coins, but it's\n"
	.string "very difficult to get.$"

MauvilleCity_GameCorner_Text_182420:: @ 8182420
	.string "You can't play if you don't have a\n"
	.string "Coin Case.$"

MauvilleCity_GameCorner_Text_GetMon::
	.string "{PLAYER} received {STR_VAR_1}!$"

MauvilleCity_GameCorner_Text_NoRoom::
    .string "Your party is full.$"

MauvilleCity_GameCorner_Text_AlreadyHaveTM::
    .string "You already have that TM.$"
