VerdanturfTown_House_Text_178D11:: @ 8178D11
	.string "Far away, deep in Ever Grande City,\n"
	.string "is the Pokémon League.\p"
	.string "The Trainers who gather there are\n"
	.string "all frighteningly well skilled.$"

VerdanturfTown_House_Text_178D8E:: @ 8178D8E
	.string "In the Pokémon League, I think the\n"
	.string "rules say that you have to battle the\l"
	.string "Elite Four all in a row.\p"
	.string "If you lose to any of them, you have\n"
	.string "to begin your challenge again from the\l"
	.string "first one.$"
