Route104_Text_16DA13:: @ 816DA13
	.string "That seaside cottage is where\n"
	.string "Mr. Briney lives.\p"
	.string "He was once a mighty sailor who never\n"
	.string "feared the sea, however stormy.$"

Route104_Text_16DA89:: @ 816DA89
	.string "The sea, huh?\p"
	.string "I wonder what it's like at the bottom\n"
	.string "of the sea?$"

Route104_Text_16DAC9:: @ 816DAC9
	.string "If you're going to throw a Poké Ball,\n"
	.string "weaken the wild Pokémon first.\p"
	.string "It will be easier to catch if it's been\n"
	.string "poisoned, burned, or lulled to sleep.$"

Route104_Text_16DB5C:: @ 816DB5C
	.string "You're a thief if you try to steal\n"
	.string "someone else's Pokémon.\p"
	.string "You should throw Poké Balls only at\n"
	.string "wild Pokémon.$"

Route104_Text_16DBC9:: @ 816DBC9
	.string "Oh, no, I'm not a Trainer.\p"
	.string "But that's right, if Trainers lock eyes,\n"
	.string "it's a challenge to battle.\p"
	.string "If you don't want to battle, stay out\n"
	.string "of their sight.$"

Route104_Text_16DC5F:: @ 816DC5F
	.string "I like tripping people with sticks,\n"
	.string "and then laughing when they fall down!\p"
	.string "You can have this, so you try it out!\p"
	.string "Use it on a Pokémon, and it will learn\n"
	.string "a move for tripping other Pokémon.$"

Route104_Text_16DD0E:: @ 816DD0E
	.string "A word of advice!\p"
	.string "A TM, Technical Machine, is good for\n"
	.string "any number of uses.\p"
    .string "Don't be afraid to experiment!$"

Route104_Text_16DD91:: @ 816DD91
	.string "This Flower Shop started selling\n"
	.string "saplings recently.\p"
	.string "It made me so happy, I went overboard\n"
	.string "shopping. I don't need this White Herb\l"
	.string "anymore. Would you take it, please?$"

Route104_Text_16DE36:: @ 816DE36
	.string "This Flower Shop started selling\n"
	.string "saplings recently.\p"
	.string "It made me so happy, I went overboard\n"
	.string "shopping. Where should I put them?$"

Route104_Text_16DEB3:: @ 816DEB3
	.string "MR. BRINEY'S COTTAGE$"

Route104_Text_16DEC8:: @ 816DEC8
	.string "ROUTE 1O4\n"
	.string "{0x7C} PETALBURG CITY$"

Route104_Text_16DEE3:: @ 816DEE3
	.string "ROUTE 1O4\n"
	.string "{0x79} RUSTBORO CITY$"

Route104_Text_16DEFD:: @ 816DEFD
	.string "PRETTY PETAL FLOWER SHOP$"

Route104_Text_16DF16:: @ 816DF16
	.string "TRAINER TIPS\p"
	.string "In the Hoenn region there are pairs\n"
	.string "of Trainers who challenge others\l"
	.string "for 2-on-2 Pokémon battles called\l"
	.string "Double Battles.\p"
	.string "In a Double Battle, the Trainer must\n"
	.string "send out two Pokémon, the one at the\l"
	.string "left of the list and the top one.\l"
	.string "Watch how Pokémon are lined up.$"
