AbandonedShip_CaptainsOffice_Text_198C85:: @ 8198C85
	.string "I'm investigating this ship on behalf\n"
	.string "of Capt. Stern.\p"
	.string "He also asked me to find a Scanner,\n"
	.string "but I haven't had any success...$"

AbandonedShip_CaptainsOffice_Text_198D00:: @ 8198D00
	.string "Oh! That's a Scanner!\p"
	.string "Listen, can I get you to deliver that\n"
	.string "to Capt. Stern?\p"
	.string "I want to investigate this ship a\n"
	.string "little more.$"

AbandonedShip_CaptainsOffice_Text_198D7B:: @ 8198D7B
	.string "This ship is called S.S. Cactus.\n"
	.string "It seems to be from an earlier era.$"
