FallarborTown_ContestHall_Text_177335:: @ 8177335
	.string "We do all right in the preliminary round,\n"
	.string "but we can never win the appeals...\p"
	.string "Maybe it means I have to watch what\n"
	.string "other contestants are doing...$"

FallarborTown_ContestHall_Text_1773C6:: @ 81773C6
	.string "See!\n"
	.string "My Pokémon won all these Ribbons!\p"
	.string "Have your Pokémon earned any Robbons?\n"
	.string "You can check them on your Pokénav.$"

FallarborTown_ContestHall_Text_177437:: @ 8177437
	.string "I can't beat Gym Leaders...\p"
	.string "I can't win any Contests...\p"
	.string "I've been here, there, and everywhere,\n"
	.string "and it's all for naught...$"

FallarborTown_ContestHall_Text_1774B1:: @ 81774B1
	.string "POKéMON CONTESTS\n"
	.string "SUPER RANK STAGE!$"
