RustboroCity_CuttersHouse_Text_18509C:: @ 818509C
	.string "That determined expression...\n"
	.string "That limber way you move...\l"
	.string "And your well-trained Pokémon...\p"
	.string "You're obviously a skilled Trainer!\p"
	.string "No, wait, don't say a word.\n"
	.string "I can tell just by looking at you.\p"
	.string "I'm sure that you will be capable\n"
	.string "of putting this HM to good use.\p"
	.string "No need to be modest or shy.\n"
	.string "Go on, take it!$"

RustboroCity_CuttersHouse_Text_1851C9:: @ 81851C9
	.string "That HM, it's Cut.\p"
	.string "An HM move is one that can be used\n"
	.string "by Pokémon out of a battle.\p"
	.string "Any Pokémon that's learned Cut can\n"
	.string "chop down thin trees if the Trainer\l"
	.string "has earned the Stone Badge.$

RustboroCity_CuttersHouse_Text_1852B3:: @ 81852B3
	.string "When they were expanding the city of\n"
	.string "Rustboro, my dad helped out.\p"
	.string "He made his Pokémon use Cut to clear\n"
	.string "the land of trees.$"
