RusturfTunnel_Text_194159:: @ 8194159
	.string "What, are you coming?\n"
	.string "Come and get some, then!$"

RusturfTunnel_Text_194188:: @ 8194188
	.string "PEEKO: Pii pihyoh!$"

RusturfTunnel_Text_19419B:: @ 819419B
	.string "Grah, keelhaul it all!\p"
	.string "That hostage Pokémon turned out to\n"
	.string "be worthless!\p"
	.string "And to think I made a getaway...\n"
	.string "In this tunnel to nowhere!\p"
	.string "Hey! You!\n"
	.string "So you want to battle me?$"

RusturfTunnel_Text_194243:: @ 8194243
	.string "Urrrggh! My career in crime comes to\n"
	.string "a dead end!$"

RusturfTunnel_Text_194274:: @ 8194274
	.string "This is plain not right...\p"
	.string "The Boss told me this would be a\n"
	.string "slick-and-easy job to pull.\p"
	.string "All I had to do was steal some package\n"
	.string "from Devon.\p"
	.string "Tch!\n"
	.string "You want it back that badly, take it!$"

RusturfTunnel_Text_19432A:: @ 819432A
	.string "Peeko! Am I glad to see you're safe!$"

RusturfTunnel_Text_19434F:: @ 819434F
	.string "Peeko owes her life to you!\p"
	.string "They call me Mr. Briney.\n"
	.string "And, you are?\p"
	.string "... ... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "Ah, so you are {PLAYER}{KUN}!\n"
	.string "I sincerely thank you!\p"
	.string "Now, if there's anything that troubles\n"
	.string "you, don't hesitate to tell me!\p"
	.string "You can usually find me in my cottage\n"
	.string "by the sea near Petalburg Woods.\p"
	.string "Come, Peeko, we should make our way\n"
	.string "home.\p"
	.string "PEEKO: Pihyoh!$"

RusturfTunnel_Text_1944C5:: @ 81944C5
	.string "... ...\p"
	.string "Why can't they keep digging?\n"
	.string "Is the bedrock too hard?\p"
	.string "My beloved awaits me in Verdanturf\n"
	.string "Town just beyond here...\p"
	.string "If Rustboro and Verdanturf were\n"
	.string "joined by this tunnel, I could visit\l"
	.string "her every day...\p"
	.string "But this...\n"
	.string "What am I to do?$"

RusturfTunnel_Text_1945B2:: @ 81945B2
	.string "To get from Rustboro to Verdanturf,\n"
	.string "you need to go to Dewford, then pass\l"
	.string "through Slateport and Mauville...$"

RusturfTunnel_Text_19461D:: @ 819461D
	.string "Wow! You shattered that boulder\n"
	.string "blocking the way.\p"
	.string "To show you how much I appreciate it,\n"
	.string "I'd like you to have this TM.$"

RusturfTunnel_Text_194693:: @ 8194693
	.string "That TM contains Bulldoze.\p"
	.string "We were going to use it to dig\n"
	.string "this tunnel, but it's far too\l"
	.string "loud for the job.$"

RusturfTunnel_Text_194706:: @ 8194706
	.string "Wanda!\n"
	.string "Now I can see you anytime!\p"
	.string "WANDA: That's...wonderful.\p"
	.string "Please, take some rest at my home.$"

RusturfTunnel_Text_194766:: @ 8194766
	.string "On the other side of this rock...\n"
	.string "My boyfriend is there.\p"
	.string "He... He's not just digging the tunnel\n"
	.string "to come see me.\p"
	.string "He works his hands raw and rough\n"
	.string "for the benefit of everyone.$"

RusturfTunnel_Text_194814:: @ 8194814
	.string "What do you call a wild man up in the\n"
	.string "mountains? A mountain man, right?\p"
	.string "So why don't they call a Pokémon in the\n"
	.string "mountains a mountain Pokémon?$"

RusturfTunnel_Text_1948A2:: @ 81948A2
	.string "My Pokémon...\n"
	.string "Ran out of power...$"

RusturfTunnel_Text_1948C4:: @ 81948C4
	.string "They halted development here to\n"
	.string "protect Pokémon, right?\l"
	.string "There's a feel-good story!$"
