LilycoveCity_DepartmentStore_3F_Text_18C24B:: @ 818C24B
	.string "For quickly toughening up Pokémon,\n"
	.string "items are the best.\p"
	.string "Protein boosts Attack, and Calcium\n"
	.string "raises Sp. Atk.$"

LilycoveCity_DepartmentStore_3F_Text_18C2B5:: @ 818C2B5
	.string "I want my Pokémon to have more\n"
	.string "endurance.\p"
	.string "I'm trying to decide whether to raise\n"
	.string "Defense with Iron, or Sp. Def with Zinc.$"

LilycoveCity_DepartmentStore_3F_Text_18C32E:: @ 818C32E
	.string "I gave a Carbos to my Pokémon and its\n"
	.string "Speed went up.$"

UnknownString_818C363: @ 818C363
	.string "ESSENTIALS FOR UNBEATABLE TRAINERS\n"
	.string "3F: BATTLE COLLECTION$"
