FabledCave_EventObjects::
	object_event 1, EVENT_OBJ_GFX_HO_OH, 0, 15, 11, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, FabledCave_EventScript_Ho_oh, FLAG_HIDE_HO_OH
	object_event 2, EVENT_OBJ_GFX_GOLD_BALL, 0, 15, 46, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, FabledCave_EventScript_TM60, FLAG_ITEM_FABLED_CAVE_TM

FabledCave_MapWarps::
	warp_def 15, 59, 0, 0, MAP_ROUTE136

FabledCave_MapEvents::
	map_events FabledCave_EventObjects, FabledCave_MapWarps, 0x0, 0x0
