TopSecretArea_Text_TorchicDoll::
    .string "It's a cute Torchic Doll.\p"
    .string "It's been illegally placed on the\n"
    .string "floor instead of on a table or rug.$"

TopSecretArea_Text_Machoke::
    .string "This Machoke with a box is\n"
    .string "monitoring the server farm.\p"
    .string "A note on the box indicates\n"
    .string "that this is an immigrant from ORAS.$"

TopSecretArea_Text_Computer1::
    .string "If you're wondering what Abilities\n"
    .string "a Pokémon can have, check the Pokédex.\p"
    .string "It has a function to show Abilities and\n"
    .string "base stats of Pokémon you've caught.$"

TopSecretArea_Text_Computer2::
    .string "If you press Select while looking at\n"
    .string "a Pokémon's stats, you can check IVs.\p"
    .string "Don't worry too much if they're not good.\n"
    .string "They're low for most enemies, too.$"

TopSecretArea_Text_Computer3::
    .string "Shoal Cave, New Mauville,\n"
    .string "Fiery Path...\p" 
    .string "Scorched Slab, Verdanturf Woods,\n"
    .string "Evergrande City...$"

TopSecretArea_Text_Computer4::
    .string "Certain legendary mirages are\n"
    .string "only visible to those who have\l"
    .string "previously seen beyond the veil.$"

TopSecretArea_Text_Computer5::
    .string "This machine has downloaded and\n"
    .string "deleted Pokémon Blue 173,637 times.\p"
    .string "Apparently, this costs Nintendo\n"
    .string "over 5 billion dollars so far.$"

TopSecretArea_Text_Computer6::
    .string "SERVER FARM\n"
    .string "Growing 100% natural servers$"

TopSecretArea_Text_Moulder::
    .string "I am MOULDER the BOULDER.\n"
    .string "I guard this item ball.\p"
    .string "Trainer, you are not yet strong\n"
    .string "enough to pass me.$"

TopSecretArea_Text_Moulder2::
    .string "I am MOULDER the BOULDER.\n"
    .string "I guard this item ball.\p"
    .string "Trainer, you are not yet strong\n"
    .string "enough to pass me.\p"
    .string "Even with your Strength, I will\n"
    .string "remain resolute and unmoving.$"

TopSecretArea_Text_Moulder3::
    .string "I am MOULDER the BOULDER.\p"
    .string "Your strength is true.\n"
    .string "You may use the infinite money ball.$"

TopSecretArea_Text_Hacker1::
    .string "Yo, welcome to my Secret Base!\p"
    .string "Hope you're liking the hack so far.\n"
    .string "It's a lot of work, even if it's simple.\p"
    .string "If things are too easy for you, swing\n"
    .string "on by here when you're Champion.\p"
    .string "I like seeing how strong Trainers respond\n"
    .string "to overwhelming challenges.$"

TopSecretArea_Text_Hacker2::
    .string "Yo, welcome to my Secret Base!\p"
    .string "Hope you're liking the hack so far.\n"
    .string "It's a lot of work, even if it's simple.\p"
    .string "I see you've beaten the Champion.\n"
    .string "In the mood for a nice battle?\p"
    .string "Fair warning; my team is...not polite.\p"
    .string "It wouldn't be wrong to liken my style\n"
    .string "of battling to literally cheating.\p"
    .string "So, wanna throw down?$"

TopSecretArea_Text_Hacker3::
    .string "Hey, no pressure.\n"
    .string "Superbosses aren't for everyone.$"

TopSecretArea_Text_Hacker4::
    .string "Alright, let's go!$"

TopSecretArea_Text_Hacker5::
    .string "Hey, good game!\n"
    .string "Hope you enjoyed the match!$"

TopSecretArea_Text_Hacker6::
    .string "Well, I'm sure you don't need much\n"
    .string "if you're strong enough to beat me,\l"
    .string "but you deserve a reward for that.\p"
    .string "Go see MOULDER the BOULDER.\n"
    .string "He'll give you your prize.$"

TopSecretArea_Text_Hacker7::
    .string "Huh, back again?\n"
    .string "Looking for a rematch?$"

TopSecretArea_Text_Plaque::
    .string "Super Secret Hack Lord Base\n"
    .string "No Game Freaks Allowed$"





