SootopolisCity_House8_Text_1900F7:: @ 81900F7
	.string "Do you know the Pokémon Shroomish?\n"
	.string "It's hardly ever seen in Sootopolis.\p"
	.string "Anyway, I love big Shroomish.\n"
	.string "The bigger the better.\p"
	.string "But my younger brother, he says that\n"
	.string "Barboach is bigger.\p"
	.string "That's silly. Shroomish has to be\n"
	.string "bigger than that!\p"
	.string "Huh? Do you have a Shroomish with you?\n"
	.string "P-p-please, show me!$"

SootopolisCity_House8_Text_19021D:: @ 819021D
	.string "{STR_VAR_2} inches!\n"
	.string "Oh, my gosh, this is a big one!\p"
	.string "It might even beat the big Barboach\n"
	.string "my younger brother saw!\p"
	.string "Thanks for showing me.\n"
	.string "This is my thanks!$"

UnknownString_81902AE: @ 81902AE
	.string "{PLAYER} received a Potion.$"

SootopolisCity_House8_Text_1902C4:: @ 81902C4
	.string "Hunh?\n"
	.string "Your Bag is crammed full.$"

SootopolisCity_House8_Text_1902E4:: @ 81902E4
	.string "{STR_VAR_2} inches, is it?\p"
	.string "Hmm... I've seen a bigger Shroomish\n"
	.string "than this one.$"

SootopolisCity_House8_Text_190329:: @ 8190329
	.string "Oh, now this is quite something...\n"
	.string "But it's not a Shroomish!$"

SootopolisCity_House8_Text_190366:: @ 8190366
	.string "You don't have a big Shroomish?\n"
	.string "That's too bad...\p"
	.string "If you get a big Shroomish, please\n"
	.string "come show me.$"

SootopolisCity_House8_Text_1903C9:: @ 81903C9
	.string "The biggest Shroomish in history!\n"
	.string "{STR_VAR_2}'s {STR_VAR_3}-inch giant!\p"
	.string "A Shroomish bigger than a Barboach\n"
	.string "always wanted!$"

SootopolisCity_House8_Text_190431:: @ 8190431
	.string "Do you know the Pokémon Barboach?\n"
	.string "It's rarely seen in Sootopolis.\p"
	.string "I love, I mean love, big Barboach!\p"
	.string "My big brother says that Shroomish is\n"
	.string "bigger.\p"
	.string "But that's wrong! Everyone knows that\n"
	.string "Barboach is a lot bigger.\p"
	.string "Hunh? Do you have a Barboach?\n"
	.string "P-p-please show me!$"

SootopolisCity_House8_Text_190536:: @ 8190536
	.string "{STR_VAR_2} inches!\n"
	.string "Wow, that is big!\p"
	.string "It might be even bigger than the huge\n"
	.string "Shroomish my big brother saw.\p"
	.string "Thanks for showing me!\n"
	.string "This is my thanks!$"

SootopolisCity_House8_Text_1905C1:: @ 81905C1
	.string "Whoops, looks like your Bag is full.$"

SootopolisCity_House8_Text_1905E6:: @ 81905E6
	.string "{STR_VAR_2} inches?\p"
	.string "Hmm... I've seen a bigger Barboach\n"
	.string "than this one here.$"

SootopolisCity_House8_Text_190628:: @ 8190628
	.string "Well, isn't this something!\n"
	.string "But it's no Barboach!$"

SootopolisCity_House8_Text_19065A:: @ 819065A
	.string "Don't you have a big Barboach?\n"
	.string "How disappointing...\p"
	.string "If you get a big Barboach, please\n"
	.string "come show me!$"

SootopolisCity_House8_Text_1906BE:: @ 81906BE
	.string "The biggest Barboach in history!\n"
	.string "{STR_VAR_2}'s {STR_VAR_3}-inch colossus!\p"
	.string "A Barboach bigger than a Shroomish\n"
	.string "always wanted!$"
