Route110_SeasideCyclingRoadSouthEntrance_Text_19E326:: @ 819E326
	.string "On Cycling Road, you can go all out\n"
	.string "and cycle as fast as you'd like.\p"
	.string "It feels great to go that fast, but try\n"
	.string "not to crash into anyone!$"

Route110_SeasideCyclingRoadNorthEntrance_Text_19E3AD:: @ 819E3AD
Route110_SeasideCyclingRoadSouthEntrance_Text_19E3AD:: @ 819E3AD
	.string "Sorry, you can't walk on Cycling\n"
	.string "Road. It's too dangerous.\p"
	.string "Please come back with a Bike.$"
