PetalburgCity_House2_Text_17BC4F:: @ 817BC4F
	.string "Norman became our town's new Gym\n"
	.string "Leader.\p"
	.string "I think he called his family over from\n"
	.string "the Johto region.$"

PetalburgCity_House2_Text_17BCB1:: @ 817BCB1
	.string "I battled Norman once, but, whew,\n"
	.string "he was way too strong.\p"
	.string "How would I put it?\p"
	.string "I just got the feeling that he\n"
	.string "lives for Pokémon.$"
