SootopolisCity_House1_Text_18F991:: @ 818F991
	.string "For thirty years I've remained in\n"
	.string "Sootopolis honing my skills.\p"
	.string "I developed a destructive TM.\n"
	.string "I bequeath it to you!$"

SootopolisCity_House1_Text_18FA03:: @ 818FA03
	.string "TM49 contains Superpower! It's a move\n"
	.string "so horrible that I can't describe it.$"

SootopolisCity_House1_Text_18FA50:: @ 818FA50
	.string "KECLEON: Puu puhyaah.$"
