MossdeepCity_Text_1690A9:: @ 81690A9
	.string "I got this from Steven, but I don't\n"
	.string "know what it's good for.\p"
	.string "I think it's called King's Rock.\n"
	.string "Do you want it?$"

MossdeepCity_Text_169117:: @ 8169117
	.string "Why would you want it?\n"
	.string "You're weird.\p"
	.string "You can keep it, but keep it a secret\n"
	.string "from Steven.$"

MossdeepCity_Text_16916F:: @ 816916F
	.string "Is it really that fun collecting\n"
	.string "rocks? I don't get it.$"

MossdeepCity_Text_1691A7:: @ 81691A7
	.string "Yeah, you think so, too! What are you\n"
	.string "supposed to do with some weird rock?$"

MossdeepCity_Text_1691F2:: @ 81691F2
	.string "Around Mossdeep, you can see wild\n"
	.string "Wailmer.\p"
	.string "It's called, uh...\n"
	.string "What was it now...\p"
	.string "Wai, Wai, Wai...\p"
	.string "Wailmer watching!$"

MossdeepCity_Text_169266:: @ 8169266
	.string "The island's Space Center has been\n"
	.string "launching huge rockets.$"

MossdeepCity_Text_1692A1:: @ 81692A1
	.string "I'd heard from my mates in Lilycove\n"
	.string "that the herd of Wailmer has\l"
	.string "disappeared.\p"
	.string "What went down over there, I wonder?$"

MossdeepCity_Text_169314:: @ 8169314
	.string "Wouldn't it be nice?\p"
	.string "If the whole world was covered in\n"
	.string "plants and flowers like this island?$"

MossdeepCity_Text_169370:: @ 8169370
	.string "All life needs the sea to live, even\n"
	.string "though it makes its home on the land.\p"
	.string "Life, having run its course, becomes\n"
	.string "soil and returns to the land.\p"
	.string "And the sea is always connected to\n"
	.string "the land.\p"
	.string "Yes, like the very shoreline here.$"

MossdeepCity_Text_16944E:: @ 816944E
	.string "A voyage on a ship is fine.\p"
	.string "But crossing the sea with Pokémon\n"
	.string "using Surf...\p"
	.string "Now that's an exhilarating trip!\n"
	.string "Wouldn't you agree, youngster?$"

MossdeepCity_Text_1694DA:: @ 81694DA
	.string "This rock has a special meaning to\n"
	.string "the people at the Space Center.\p"
	.string "They put it here as their wish for\n"
	.string "their rockets to fly safely.\p"
	.string "When you make a wish, what do you use?\n"
	.string "Do you wish upon a star?\p"
	.string "I use a wish tag to make it happen.\n"
	.string "That's what I do.$"

MossdeepCity_Text_1695D3:: @ 81695D3
	.string "It's a white rock.$"

MossdeepCity_Text_1695E6:: @ 81695E6
	.string "MOSSDEEP CITY POKéMON GYM\n"
	.string "LEADER: LIZA\p"
	.string "“The mystic prodigy!”$"

MossdeepCity_Text_16962F:: @ 816962F
	.string "MOSSDEEP CITY\n"
	.string "“Our slogan: Cherish Pokémon!”$"

MossdeepCity_Text_16965C:: @ 816965C
	.string "MOSSDEEP SPACE CENTER\n"
	.string "“The closest place to space.”$"

MossdeepCity_Text_AquaGruntMeet::
    .string "Hey, you!\n"
    .string "{PLAYER}, right?\p"
    .string "I got something for you, courtesy\n"
    .string "of Archie himself!$"

MossdeepCity_Text_AquaGruntExplain::
    .string "That's state of the art stuff!\n"
    .string "Devon tech, plus Team Aqua's science!\p"
    .string "It'll get you underwater even if none\n"
    .string "of your Pokémon know how to use Dive!\p"
    .string "Archie said he wants you to go down\n"
    .string "into the sea, after Team Magma.\p"
    .string "So you better get on it!$"
