PacifidlogTown_PokemonCenter_1F_Text_178E47:: @ 8178E47
	.string "What color is your Trainer Card?\n"
	.string "Mine's copper!$"

PacifidlogTown_PokemonCenter_1F_Text_178E79:: @ 8178E79
	.string "Pacifidlog Town floats on top of\n"
	.string "a colony of Corsola.\p"
	.string "If I told you that, would you believe me?$"

PacifidlogTown_PokemonCenter_1F_Text_178ED9:: @ 8178ED9
	.string "The ancestors of the people in\n"
	.string "Pacifidlog were said to have been\l"
	.string "born on boats and then lived and died \l"
	.string "aboard them.\p"
	.string "I understand that they lived that way\n"
	.string "because they were searching for\l"
	.string "something.$"
