SlateportCity_ContestLobby_Text_17C937:: @ 817C937
	.string "I want to raise a Pokémon that's\n"
	.string "the ultimate in “great” for both\l"
	.string "battles and Contests.\p"
	.string "It's vexing, trying to figure out\n"
	.string "which moves I should make it learn.$"

SlateportCity_ContestLobby_Text_17C9D5:: @ 817C9D5
	.string "Do any of your friends have any\n"
	.string "Berries?\p"
	.string "You can use that Berry Blender and\n"
	.string "make {POKEBLOCK}s with your friends!\p"
	.string "You should try it - it's a lot of fun!$"

SlateportCity_ContestLobby_Text_17CA67:: @ 817CA67
	.string "I have two, so you can have one!$"

SlateportCity_ContestLobby_Text_17CA88:: @ 817CA88
	.string "Make {POKEBLOCK}s and put them in there.\p"
	.string "When you make a {POKEBLOCK}, everyone\n"
	.string "has to put in a different Berry.$"

SlateportCity_ContestLobby_Text_17CAEC:: @ 817CAEC
	.string "If you win a Contest, they put up a\n"
	.string "poster of your Pokémon on the wall.\p"
	.string "It will have a portrait of your\n"
	.string "Pokémon and both your names.$"
