MossdeepCity_House2_Text_18D536:: @ 818D536
	.string "My little sister exchanges Mail with\n"
	.string "her boyfriend in Fortree.\p"
	.string "I don't envy her one bit at all.$"

MossdeepCity_House2_Text_18D596:: @ 818D596
	.string "Even though I can't see my friend in\n"
	.string "Fortree, my Pokémon carries Mail back\l"
	.string "and forth for us.\p"
	.string "I'm not lonesome, even though we're\n"
	.string "apart.$"

MossdeepCity_House2_Text_18D61E:: @ 818D61E
	.string "WINGULL: Pihyoh!$"
