GraniteCave_LugiaChamber_EventObjects::
	object_event 1, EVENT_OBJ_GFX_LUGIA, 0, 15, 7, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, GraniteCave_LugiaChamber_EventScript_Lugia, FLAG_HIDE_LUGIA
	object_event 2, EVENT_OBJ_GFX_GOLD_BALL, 0, 22, 23, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, GraniteCave_LugiaChamber_EventScript_TM60, FLAG_ITEM_LUGIA_CHAMBER_TM

GraniteCave_LugiaChamber_MapWarps::

GraniteCave_LugiaChamber_MapEvents::
	map_events GraniteCave_LugiaChamber_EventObjects, GraniteCave_LugiaChamber_MapWarps, 0x0, 0x0
