LilycoveCity_House3_Text_18B8CC:: @ 818B8CC
	.string "Oh, my, my! Are you traveling alone?\n"
	.string "But you're so young! Good for you!\p"
	.string "I'm sure my kids could learn a thing\n"
	.string "or two from you!\p"
	.string "Me? I'm a master of {POKEBLOCK}s.\p"
	.string "If I get serious just a little, why, I\n"
	.string "can concoct great {POKEBLOCK}s.\p"
	.string "Would you like to learn from me, a\n"
	.string "master of {POKEBLOCK}s?$"

LilycoveCity_House3_Text_18B9DC:: @ 818B9DC
	.string "Oh? Are you sure?\p"
	.string "You shouldn't always try to do\n"
	.string "everything by yourself, dear!$"

LilycoveCity_House3_Text_18BA2B:: @ 818BA2B
	.string "Oh, good! You're a smart soul!\n"
	.string "This is a bit long, so listen up!\p"
	.string "Are you ready?\p"
	.string "If you look at {POKEBLOCK}s, you should see\n"
	.string "that they are rated on how they feel.\p"
	.string "The lower the feel rating,\n"
	.string "the better it is. Don't forget this!\p"
	.string "A good {POKEBLOCK} has a low feel\n"
	.string "rating and a high level.\p"
	.string "A Pokémon can eat more good\n"
	.string "{POKEBLOCK}s than ordinary ones, too.\p"
	.string "And this is important.\p"
	.string "If you want to make smooth {POKEBLOCK}s,\n"
	.string "use different kinds of Berries.\p"
	.string "Don't be stingy - the kinds of Berries\n"
	.string "affect the smoothness of {POKEBLOCK}s.\p"
	.string "And another thing.\p"
	.string "The more people blending Berries, the\n"
	.string "smoother the {POKEBLOCK}s.\p"
	.string "That's why you should talk to other\n"
	.string "people and make {POKEBLOCK}s together.\p"
	.string "That's about all you need to know to\n"
	.string "make good {POKEBLOCK}s.\p"
	.string "If everyone had Pokémon they love,\n"
	.string "smooth {POKEBLOCK}s, and a loving family,\l"
	.string "the world would be a happier place.\p"
	.string "Don't give up, dear!$"

LilycoveCity_House3_Text_18BD64:: @ 818BD64
	.string "When my wife gave birth to quadruplets,\n"
	.string "you bet I was shocked.\p"
	.string "But, now, seeing them play together,\n"
	.string "it makes me happy.$"

LilycoveCity_House3_Text_18BDDB:: @ 818BDDB
	.string "We're having Multi Battles, but I know\n"
	.string "I'm going to win.$"

LilycoveCity_House3_Text_18BE14:: @ 818BE14
	.string "We like mixing stuff at the Record\n"
	.string "Corner.\p"
	.string "But what gets mixed up?$"

LilycoveCity_House3_Text_18BE57:: @ 818BE57
	.string "We're going to make super {POKEBLOCK}s\n"
	.string "with a Berry Blender!$"

LilycoveCity_House3_Text_18BE8E:: @ 818BE8E
	.string "I want to brag about how tough my\n"
	.string "Pokémon is, so we're going to enter a\l"
	.string "Contest together.$"
