RustboroCity_Mart_Text_184C76:: @ 8184C76
	.string "I'm buying some Parlyz Heals and\n"
	.string "Antidotes.\p"
	.string "Just in case I run into Shroomish\n"
	.string "or Paras in Petalburg Woods.$"

RustboroCity_Mart_Text_184CD8:: @ 8184CD8
	.string "My Pokémon evolved.\n"
	.string "It has a lot of HP now.\p"
	.string "I should buy Super Potions for it\n"
	.string "instead of ordinary Potions.$"

RustboroCity_Mart_Text_184D43:: @ 8184D43
	.string "I'm getting an Escape Rope just in\n"
	.string "case I get lost in a cave.\p"
	.string "I just need to use it to get back to the\n"
	.string "entrance.$"
