SootopolisCity_Mart_Text_18F890:: @ 818F890
	.string "PP Up is great!\p"
	.string "It raises the Power Points, the PP,\n"
	.string "of a Pokémon move.$"

SootopolisCity_Mart_Text_18F8D7:: @ 818F8D7
	.string "What... What is happening?$"

SootopolisCity_Mart_Text_18F8F2:: @ 818F8F2
	.string "Do you know Full Restore?\p"
	.string "Full restoration of HP!\n"
	.string "Eradication of all status problems!\p"
	.string "It's truly an item of your dreams!$"

SootopolisCity_Mart_Text_18F96B:: @ 818F96B
	.string "This weather...\n"
	.string "Did something awaken?$"
