TracklessForest_EventObjects::
    object_event 1, EVENT_OBJ_GFX_SUDOWOODO, 0, 7, 37, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, 0, 0, TracklessForest_EventScript_Sudowoodo, FLAG_HIDE_SUDOWOODO

TracklessForest_MapWarps::
	warp_def 6, 42, 0, 6, MAP_PETALBURG_WOODS
	warp_def 7, 42, 0, 7, MAP_PETALBURG_WOODS

TracklessForest_MapCoordEvents::

TracklessForest_MapBGEvents::

TracklessForest_MapEvents:: @ 838C31C
	map_events TracklessForest_EventObjects, TracklessForest_MapWarps, 0, 0
