TracklessForest_EventObjects::

TracklessForest_MapWarps::
	warp_def 6, 42, 0, 6, MAP_PETALBURG_WOODS
	warp_def 7, 42, 0, 7, MAP_PETALBURG_WOODS

TracklessForest_MapCoordEvents::
	coord_event 5, 41, 3, 0, 0, Route111_EventScript_1501BC
	coord_event 6, 40, 3, 0, 0, Route111_EventScript_1501BC
	coord_event 7, 40, 3, 0, 0, Route111_EventScript_1501BC
	coord_event 8, 41, 3, 0, 0, Route111_EventScript_1501BC
	coord_event 4, 39, 3, 0, 0, Route111_EventScript_1501C9
	coord_event 5, 39, 3, 0, 0, Route111_EventScript_1501C9
	coord_event 6, 39, 3, 0, 0, Route111_EventScript_1501C9
	coord_event 7, 39, 3, 0, 0, Route111_EventScript_1501C9
	coord_event 8, 39, 3, 0, 0, Route111_EventScript_1501C9
	coord_event 9, 39, 3, 0, 0, Route111_EventScript_1501C9
	coord_event 4, 37, 3, VAR_TEMP_3, 0, Route111_EventScript_150116
	coord_event 5, 37, 3, VAR_TEMP_3, 0, Route111_EventScript_150116
	coord_event 6, 37, 3, VAR_TEMP_3, 0, Route111_EventScript_150116
	coord_event 7, 37, 3, VAR_TEMP_3, 0, Route111_EventScript_150116
	coord_event 8, 37, 3, VAR_TEMP_3, 0, Route111_EventScript_150116
	coord_event 9, 37, 3, VAR_TEMP_3, 0, Route111_EventScript_150116

TracklessForest_MapBGEvents::

TracklessForest_MapEvents:: @ 838C31C
	map_events TracklessForest_EventObjects, TracklessForest_MapWarps, TracklessForest_MapCoordEvents, 0
