TracklessForest_Text_WeirdTree::
    .string "It's a weird tree...\n"
    .string "Use the Wailmer Pail?$"

TracklessForest_Text_WaterTree::
    .string "{PLAYER} watered the weird tree.$"

TracklessForest_Text_SudowoodoSandstorm::
    .string "The tree whipped up a sandstorm...\n"
    .string "It's too vicious to linger here!$"

TracklessForest_Text_SudowoodoAttacked::
    .string "The tree whipped up a vicious\n"
    .string "sandstorm and attacked!$"

TracklessForest_Text_BenjaminSpot::
    .string "Let me hear your Pokemon...\n"
    .string "Show me the pathos of your will!$"

TracklessForest_Text_BenjaminDefeat::
    .string "Aiiiyaaaaaah!$"

TracklessForest_Text_BenjaminFollowup::
    .string "Shh. Let me listen to the sounds\n"
    .string "of this rock in peace.$"

TracklessForest_Text_LeahSpot::
    .string "This place...\n"
    .string "The other world blossoms here...$"

TracklessForest_Text_LeahDefeat::
    .string "Ah...$"

TracklessForest_Text_LeahFollowup::
    .string "Something spiritual is in the air.\n"
    .string "Watch yourself.$"

TracklessForest_Text_HarrisonSpot::
    .string "Attention: Today is frog day.$"

TracklessForest_Text_HarrisonDefeat::
    .string "Wow, lame.$"

TracklessForest_Text_HarrisonFollowup::
    .string "Frogs are the most important creatures\n"
    .string "on Earth. This is an objective fact.$"
