TracklessForest_Text_WeirdTree::
    .string "It's a weird tree...\n"
    .string "Use the Wailmer Pail?$"

TracklessForest_Text_WaterTree::
    .string "{PLAYER} watered the weird tree.$"

TracklessForest_Text_SudowoodoSandstorm::
    .string "The tree whipped up a sandstorm...\n"
    .string "It's too vicious to linger here!$"

TracklessForest_Text_SudowoodoAttacked::
    .string "The tree whipped up a vicious\n"
    .string "sandstorm and attacked!$"
