RustboroCity_House3_Text_185584:: @ 8185584
	.string "For my own Pokémon, I give them\n"
	.string "perfectly suited nicknames!\p"
	.string "It's my expression of, uh...\n"
	.string "originality, yes, that's it!$"

RustboroCity_House3_Text_1855FA:: @ 81855FA
	.string "But giving the name Jeff to all\n"
	.string "of your Pikachu? It makes no sense.\p"
	.string "How do you tell them apart?$"

RustboroCity_House3_Text_18567D:: @ 818567D
	.string "JEFF: Peka!$"
