AquaHideout_B1F_Text_196E6F:: @ 8196E6F
	.string "If you want to know the secret about\n"
	.string "our HIDEOUT, you have me to beat!$"

AquaHideout_B1F_Text_196EB6:: @ 8196EB6
	.string "I can't win at all...$"

AquaHideout_B1F_Text_196ECC:: @ 8196ECC
	.string "Our HIDEOUT's secret?\p"
	.string "Well, let's just say...\n"
	.string "There's a submarine at the far end!\p"
	.string "But, by now...\n"
	.string "Kekekeke...$"

AquaHideout_B1F_Text_196F39:: @ 8196F39
	.string "Fuel supply loaded A-OK!\n"
	.string "In-cruise snacks loaded A-OK!\p"
	.string "Nothing left to do but KO a pesky\n"
	.string "meddler!$"

AquaHideout_B1F_Text_196F9B:: @ 8196F9B
	.string "I took a serious licking!$"

AquaHideout_B1F_Text_196FB5:: @ 8196FB5
	.string "Humph!\n"
	.string "This was supposed to happen!\p"
	.string "My mission was to just hold you up!$"

AquaHideout_B1F_Text_196FFD:: @ 8196FFD
	.string "Yawn... Keeping watch over the\n"
	.string "HIDEOUT bores me. I'll take you on.$"

AquaHideout_B1F_Text_197040:: @ 8197040
	.string "Yawn...\n"
	.string "Oh, I lost...$"

AquaHideout_B1F_Text_197056:: @ 8197056
	.string "If you scurry too much, other TEAM\n"
	.string "{EVIL_TEAM} members might get you.$"

MagmaHideout_B1F_Text_AquaGruntOneSpot::
    .string "Oh no! I'm done for!\n"
    .string "Team Magma's here to get me!$"

MagmaHideout_B1F_Text_AquaGruntOneDefeat::
    .string "Huh? You're not with them?$"

MagmaHideout_B1F_Text_AquaGruntOneLater::
    .string "I came here with Madame Shelly to jack\n"
    .string "a submarine, but...\p"
    .string "This place is like a maze!\n"
    .string "Where's the exit?$"

MagmaHideout_B1F_Text_AquaGruntTwoSpot::
    .string "This place is too hot..\n"
    .string "Do people seriously live here?$"

MagmaHideout_B1F_Text_AquaGruntTwoDefeat::
    .string "Now I'm hot and sweaty...$"

MagmaHideout_B1F_Text_AquaGruntTwoLater::
    .string "Shelly and I got separated in the\n"
    .string "teleporter maze.\p"
    .string "I hope she gets back soon...$"

MagmaHideout_B1F_Text_ShellyIntro::
    .string "Oh? I know that face.\p"
    .string "You're that brat that's been running\n"
    .string "around and meddling with everyone.\p"
    .string "I should extend an invitation to join\n"
    .string "Team Aqua, but...\p"
    .string "You still owe us one for Mt. Chimney.\n"
    .string "Get ready to be destroyed!$"

MagmaHideout_B1F_Text_ShellyDefeat::
    .string "So strong...\n"
    .string "That tired me out...$"

MagmaHideout_B1F_Text_ShellyLater::
    .string "Alright.\n"
    .string "I can see you're the real deal.\p"
    .string "I'll forgive your crimes against Team\n"
    .string "Aqua if you stop Maxie. Got it?\p"
    .string "Take this. You'll need it to get to\n"
    .string "the Submarine Explorer 1.$"

MagmaHideout_B1F_Text_ShellyLaterTwo::
    .string "Lavaridge's Gym Badge...\n"
    .string "Yeah, you'll be fine.\p"
    .string "Now, I've got to report to Archie.\n"
    .string "See you around.$"
