MauvilleCity_PokemonCenter_1F_Text_1825BD:: @ 81825BD
	.string "That man over there, he says weird\n"
	.string "things!\p"
	.string "He's funny in a weird way.\n"
	.string "I doubt I'll forget about him!$"

MauvilleCity_PokemonCenter_1F_Text_182622:: @ 8182622
	.string "When I accessed the Record Corner,\n"
	.string "the data for what's hot in Dewford\l"
	.string "got updated.\p"
	.string "Now that bit of data is the same\n"
	.string "as my friend's!$"

MauvilleCity_PokemonCenter_1F_Text_1826A6:: @ 81826A6
	.string "A Record Corner opened upstairs in\n"
	.string "the Pokémon Center.\p"
	.string "I don't know what it's about, but it\n"
	.string "sounds fun. I'll go check it out!$"

MauvilleCity_PokemonCenter_1F_Text_Man::
    .string "Hm!\n"
    .string "This world has been doctored.\p"
    .string "In another reality, I would provide\n"
    .string "a bothersome, pointless service.\p"
    .string "A strange power is at work here.\n"
    .string "Take this. Trust no one.$"

MauvilleCity_PokemonCenter_1F_Text_Man2::
    .string "Now, I must depart from this world.\n"
    .string "Let us never meet again.$"
