Route114_FossilManiacsTunnel_Text_192795:: @ 8192795
	.string "I'm the Fossil Maniac...\n"
	.string "I'm a nice guy who loves fossils...\p"
	.string "Do you want a fossil?\p"
	.string "But the fossils around these parts all\n"
	.string "belong to me... None for you...\p"
	.string "If you can't go without a fossil, go to\n"
	.string "the desert on Route 111...\p"
	.string "From what I've heard, fossils that were\n"
	.string "buried in the sand sometimes rise to\l"
	.string "the surface from sandstorms...$"

Route114_FossilManiacsTunnel_Text_1928DE:: @ 81928DE
	.string "You found a Fossil, didn't you?\n"
	.string "That's so nice... It's so dreamy...\p"
	.string "What are you going to do with that\n"
	.string "Fossil?\p"
	.string "From what I've heard, Devon is doing\n"
	.string "research on reviving Pokémon from\l"
	.string "Fossils...\p"
	.string "I love my Fossils, so I would never\n"
	.string "do anything like that...$"

Route114_FossilManiacsTunnel_Text_1929DC:: @ 81929DC
	.string "Fossils are so... Wonderful...\n"
	.string "It's so dreamy...$"
