EverGrandeCity_PokemonLeague_Text_1916FD:: @ 81916FD
	.string "Beyond this point, only those Trainers\n"
	.string "who have collected all the Gym Badges\l"
	.string "are permitted to enter.\p"
	.string "Trainer, let us confirm that you have\n"
	.string "all the Gym Badges.$"

EverGrandeCity_PokemonLeague_Text_19179C:: @ 819179C
	.string "You haven't obtained all the Badges.\p"
	.string "If you're bound for the Pokémon\n"
	.string "League, you must return with them.$"

EverGrandeCity_PokemonLeague_Text_191804:: @ 8191804
	.string "Trainer! Believe in yourself and your\n"
	.string "Pokémon, and go forth!$"
