FortreeCity_PokemonCenter_1F_Text_186027:: @ 8186027
	.string "Listen, kid, are you working\n"
	.string "on a Pokédex?\p"
	.string "Hmm... Go to the Safari Zone.\n"
	.string "That's my suggestion.$"

FortreeCity_PokemonCenter_1F_Text_186086:: @ 8186086
	.string "Have you done anything at the\n"
	.string "Record Corner?\p"
	.string "It's pretty neat. It mixes and matches\n"
	.string "the records of Trainers.\p"
	.string "I don't know quite how it works,\n"
	.string "but it's cool. It's exciting, even!$"

FortreeCity_PokemonCenter_1F_Text_186138:: @ 8186138
	.string "Hey, you've got a Pokénav!\n"
	.string "It's the same as mine.\p"
	.string "Check out the Trainer's Eyes on it.\p"
	.string "It shows you Trainers who want a\n"
	.string "rematch with you.\p"
	.string "Isn't it great?\n"
	.string "You have to hand it to Devon!$"
