RustboroCity_DevonCorp_3F_Text_18320B:: @ 818320B
	.string "I'm Mr. Stone, the President of\n"
	.string "the Devon Corporation.\p"
	.string "I'd just got word about you!\p"
	.string "You saved our staff not just once,\n"
	.string "but twice!\p"
	.string "I have a favor to ask of an amazing\n"
	.string "person like you.\p"
	.string "I understand that you're delivering\n"
	.string "a package to Slateport's Shipyard.\p"
	.string "Well, on the way, could you stop off in\n"
	.string "Dewford Town?\p"
	.string "I was hoping that you'd deliver a Letter\n"
	.string "to Steven in Dewford.$"

RustboroCity_DevonCorp_3F_Text_18337E:: @ 818337E
	.string "MR. STONE: Now, you should know that\n"
	.string "I am a great President.\p"
	.string "So, I'd never be so cheap as to ask\n"
	.string "a favor for nothing in return.\p"
	.string "That's why I want you to have this!$"

RustboroCity_DevonCorp_3F_Text_183422:: @ 8183422
	.string "{PLAYER} received a Pokénav.$"

RustboroCity_DevonCorp_3F_Text_183439:: @ 8183439
	.string "MR. STONE: That device...\p"
	.string "It's a Pokémon Navigator, or Pokénav\n"
	.string "for short.\p"
	.string "It's an indispensable tool for any\n"
	.string "Trainer on an adventure.\p"
	.string "It has a map of the Hoenn region.\p"
	.string "You can check the locations of\n"
	.string "Dewford and Slateport easily!$"

RustboroCity_DevonCorp_3F_Text_18351E:: @ 818351E
	.string "MR. STONE: I'm counting on you!$"

RustboroCity_DevonCorp_3F_Text_18353E:: @ 818353E
	.string "MR. STONE: You delivered my Letter?\n"
	.string "Thank you kindly!\p"
	.string "This is my way of thanking you.\n"
	.string "It should help you, a Trainer.$"

RustboroCity_DevonCorp_3F_Text_1835B3:: @ 81835B3
	.string "MR. STONE: A Pokémon holding that\n"
	.string "Exp. Share will be given some of the\l"
	.string "Exp. Points from battle.\p"
	.string "It will get Exp. Points even if it didn't\n"
	.string "actually battle.\p"
	.string "I would say Exp. Share is quite useful\n"
	.string "for raising weak Pokémon.$"

RustboroCity_DevonCorp_3F_Text_18368D:: @ 818368D
	.string "MR. STONE: Since my youth, I've immersed\n"
	.string "myself in work.\p"
	.string "Consequently, I'm not familiar with\n"
	.string "trends and that sort of thing.\p"
	.string "But do young people all want to be\n"
	.string "Trainers in the Pokémon League?$"

RustboroCity_DevonCorp_3F_Text_18374C:: @ 818374C
	.string "This is the Devon Corporation's\n"
	.string "third floor.\p"
	.string "Our President's Office is on this floor.\p"
	.string "Anyway, I can't tell you how much I'm\n"
	.string "grateful for what you've done.\p"
	.string "Um... By the way, that parcel you got\n"
	.string "back for us...\p"
	.string "Could I get you to deliver that to the\n"
	.string "Shipyard in Slateport?\p"
	.string "It would be awful if those robbers\n"
	.string "tried to take it again.\p"
	.string "Uh... Hehehe, so, uh, could I count\n"
	.string "on you to do that for me?\p"
	.string "Oh, that's right.\n"
	.string "Could you wait here a second?$"

RustboroCity_DevonCorp_3F_Text_183903:: @ 8183903
	.string "Our President would like to have\n"
	.string "a word with you.\p"
	.string "Please come with me.$"

RustboroCity_DevonCorp_3F_Text_18394A:: @ 818394A
	.string "Please, go ahead.$"

RustboroCity_DevonCorp_3F_Text_18395C:: @ 818395C
	.string "If you visit the Shipyard in Slateport,\n"
	.string "you should go see Capt. Stern.$"

RustboroCity_DevonCorp_3F_Text_1839A3:: @ 81839A3
	.string "Devon's new products, the Repeat Ball\n"
	.string "and Timer Ball, have become hugely\l"
	.string "popular among Trainers.$"

RustboroCity_DevonCorp_3F_Text_183A04:: @ 8183A04
	.string "It's a collection of rare rocks and\n"
	.string "stones assembled by the President.$"
