Route128_Text_171EE0:: @ 8171EE0
	.string "MAXIE: What happened...\n"
	.string "What is this wretched scene...\p"
	.string "Did I...make a horrible mistake?$"

Route128_Text_171F35:: @ 8171F35
	.string "I...\n"
	.string "I only wanted...$"

Route128_Text_171F4B:: @ 8171F4B
	.string "ARCHIE: Do you understand now,\n"
	.string "Maxie?\p"
	.string "Do you finally see how disastrous\n"
	.string "your dream turned out to be?\p"
	.string "We have to hurry! We have to do\n"
	.string "something before the situation goes\l"
	.string "completely out of control!$"

Route128_Text_172008:: @ 8172008
	.string "ARCHIE: {PLAYER}{KUN}...\p"
	.string "We, Team Aqua, had been pursuing Team\n"
	.string "Magma to prevent this from happening.\p"
	.string "You've been very helpful, but I fear\n"
	.string "the worst has happened...\p"
	.string "It's gone too far for a child like you\n"
	.string "to manage...\p"
	.string "Leave things to us, and get out of\n"
	.string "here while you still can!$"

Route128_Text_17210B:: @ 817210B
	.string "ARCHIE: This defies belief...\p"
	.string "A super-ancient Pokémon...\p"
	.string "Its power is unbelievable.\n"
	.string "It has upset the balance of nature...$"

Route128_Text_172181:: @ 8172181
	.string "STEVEN: {PLAYER}{KUN}!\n"
	.string "What is happening?$"

Route128_Text_1721A2:: @ 81721A2
	.string "This is terrible...\p"
	.string "If this doesn't stop, all Hoenn...\n"
	.string "No, the whole world will drown.\p"
	.string "This huge rain cloud is spreading\n"
	.string "from above Sootopolis?\p"
	.string "What in the world is taking place there?\p"
	.string "There's no point arguing here...\n"
	.string "Sootopolis should provide answers...$"

Route128_Text_1722A1:: @ 81722A1
	.string "This is terrible...\p"
	.string "If this doesn't stop, all of Hoenn...\n"
	.string "No, the whole world will be parched.\p"
	.string "The cause of this calamity, the blazing\n"
	.string "sun, is in the sky above Sootopolis...\p"
	.string "What in the world is taking place there?\p"
	.string "There's no point arguing here...\n"
	.string "Sootopolis should provide answers...$"

Route128_Text_1723BE:: @ 81723BE
	.string "{PLAYER}{KUN}...\n"
	.string "I don't know what you intend to do,\l"
	.string "but don't do anything reckless.\p"
	.string "Okay.\n"
	.string "I'm going to Sootopolis.$"
