FallarborTown_House2_Text_177AF4:: @ 8177AF4
	.string "I'm the MOVE TUTOR.\p"
	.string "I know all the moves that POKéMON\n"
	.string "learn - every one of them - and I can\l"
	.string "teach POKéMON those moves.\p"
	.string "I can teach a move to a POKéMON\n"
	.string "of yours if you'd like.\p"
	.string "I'll do it for a HEART SCALE.\n"
	.string "I'm collecting those now.$"

FallarborTown_House2_Text_177BDB:: @ 8177BDB
	.string "Oh! That's it! That's an honest to\n"
	.string "goodness HEART SCALE!\p"
	.string "Let me guess, you want me to teach\n"
	.string "a move?$"

FallarborTown_House2_Text_177C3F:: @ 8177C3F
	.string "Which POKéMON needs tutoring?$"

FallarborTown_House2_Text_177C5D:: @ 8177C5D
	.string "Which move should I teach?$"

FallarborTown_House2_Text_177C78:: @ 8177C78
	.string "Sorry...\p"
	.string "It doesn't appear as if I have any move\n"
	.string "I can teach that POKéMON.$"

FallarborTown_House2_Text_177CC3:: @ 8177CC3
	.string "{PLAYER} handed over one Heart Scale\n"
	.string "in exchange.$"

FallarborTown_House2_Text_177CEF:: @ 8177CEF
	.string "If your Pokémon need to learn a move,\n"
	.string "come back with a Heart Scale.$"

FallarborTown_House2_Text_177D33:: @ 8177D33
	.string "Hunh? There isn't a single move that\n"
	.string "I can teach an EGG.$"

FallarborTown_House2_Text_EggTutorHi::
    .string "I'm the Assistant Move Tutor...\p"
    .string "I know what all moves Pokémon\n"
    .string "can learn when they're first born.\p"
    .string "I can't teach them myself, though.\p"
    .string "Bring me a Pokémon that knows the\n"
    .string "move and a Heart Scale, and I'll\l"
    .string "see what we can do.$"

FallarborTown_House2_Text_EggTutorStart::
    .string "That's a Heart Scale...\n"
    .string "Shall I get to work?$"

FallarborTown_House2_Text_EggTutorWhichMon::
	.string "Which Pokémon needs looked at?$"

FallarborTown_House2_Text_EggTutorWhichMove::
	.string "Which move should it inherit?$"

FallarborTown_House2_Text_EggTutorNoMoves::
    .string "That Pokémon can't learn any\n"
    .string "moves from me...\p"
	.string "Sorry...$"

FallarborTown_House2_Text_EggTutorComeBack:: @ 8177CEF
	.string "If your want my services, please\n"
	.string "come back with a Heart Scale.$"

FallarborTown_House2_Text_EggTutorTeachesEgg::
    .string "Ah...\n"
    .string "It's a bit early for this one, isn't it?$"

