MagmaHideout_1F_Text_MagmaGruntSee::
	.string "Ayiyiyi!\n"
	.string "Insufficiently red character spotted!$"

MagmaHideout_1F_Text_MagmaGruntFight::
	.string "Grrrrr...\n"
	.string "I lost it!$"

MagmaHideout_1F_Text_MagmaGruntPost::
	.string "I took the loss for the Team, but\n"
	.string "I did my job...$"

MagmaHideout_1F_Text_AquaGruntSee::
	.string "Ayiyiyi!\n"
	.string "Suspicious red character spotted!$"

MagmaHideout_1F_Text_AquaGruntFight::
	.string "Grrrrr...\n"
	.string "I lost it!$"

MagmaHideout_1F_Text_AquaGruntPost::
	.string "I took the loss for the Team, but\n"
	.string "I did my job...$"
