FallarborTown_House1_Text_177755:: @ 8177755
	.string "PROF. COZMO: Oh...\n"
	.string "I never should have let myself be\l"
	.string "conned into telling Team Aqua where\l"
	.string "you can find Meteorites...\p"
	.string "That Meteorite from Meteor Falls...\n"
	.string "It's never going to be mine now...$"

FallarborTown_House1_Text_17780E:: @ 817780E
	.string "Oh!\n"
	.string "Hah?\p"
	.string "That item...\p"
	.string "Could it be?\p"
	.string "Is it the Meteorite that Team Aqua\n"
	.string "took from Meteor Falls?\p"
	.string "Please, may I have it?\p"
	.string "I'm not asking for it for free.\n"
	.string "How about in exchange for this TM?$"

FallarborTown_House1_Text_1778C4:: @ 81778C4
	.string "PROF. COZMO: This TM, it represents\n"
	.string "my feeling of gratitude.\l"
	.string "Please use it!$"

FallarborTown_House1_Text_177910:: @ 8177910
	.string "PROF. COZMO: Oh, I can't believe it.\n"
	.string "This is really, really great!\p"
	.string "This is really going to help my research!$"

FallarborTown_House1_Text_17797D:: @ 817797D
	.string "PROF. COZMO: Oh, but...\n"
	.string "I'm crushed with disappointment...$"

FallarborTown_House1_Text_1779B8:: @ 81779B8
	.string "PROF. COZMO: Please, may I have that\n"
	.string "Meteorite?\p"
	.string "I'm not asking for it for free.\n"
	.string "How about in exchange for this TM?$"

FallarborTown_House1_Text_177A2B:: @ 8177A2B
	.string "Prof. Cozmo went off to Meteor Falls\n"
	.string "on Route 114 with some people from\l"
	.string "Team Aqua.$"

FallarborTown_House1_Text_177A7C:: @ 8177A7C
	.string "Poor Prof. Cozmo...\n"
	.string "He's so depressed... I feel sorry for him.$"

FallarborTown_House1_Text_177ABB:: @ 8177ABB
	.string "Look at Prof. Cozmo...\n"
	.string "He's so happy! I think it's cute.$"
