SlateportCity_House2_Text_1804CF:: @ 81804CF
	.string "My Pokémon has a Hasty nature.\p"
	.string "It has higher Speed compared to my\n"
	.string "other Pokémon.\p"
	.string "Maybe their nature has something to\n"
	.string "do with the stat gains of Pokémon.$"

SlateportCity_House2_Text_180567:: @ 8180567
	.string "You need a Contest Pass to enter a\n"
	.string "Contest.\p"
	.string "It's easy to get. They give it to\n"
	.string "anyone who has Pokémon.$"

SlateportCity_House2_Text_1805CD:: @ 81805CD
	.string "Oh, a Contest Pass!\n"
	.string "You're going to be a contestant?$"
