PetalburgCity_PokemonCenter_1F_Text_17BD30:: @ 817BD30
	.string "That PC-based Pokémon storage\n"
	.string "system...\p"
	.string "Whoever made it must be some kind\n"
	.string "of a scientific wizard!$"

PetalburgCity_PokemonCenter_1F_Text_17BD92:: @ 817BD92
	.string "When my Pokémon ate an\n"
	.string "Oran Berry, it regained HP!$"

PetalburgCity_PokemonCenter_1F_Text_17BDC5:: @ 817BDC5
	.string "There are many types of Pokémon.\p"
	.string "All types have their strengths and\n"
	.string "weaknesses against other types.\p"
	.string "Depending on the types of Pokémon,\n"
	.string "a battle could be easy or hard.$"

PetalburgCity_PokemonCenter_1F_Text_17BE6C:: @ 817BE6C
	.string "For example, your Treecko is a\n"
	.string "Grass type.\p"
	.string "It's strong against the Water and\n"
	.string "Ground types.\p"
	.string "But, it's weak against Fire-type\n"
	.string "Pokémon.$"

PetalburgCity_PokemonCenter_1F_Text_17BEF1:: @ 817BEF1
	.string "For example, your Torchic is a\n"
	.string "Fire type.\p"
	.string "It's strong against the Grass and\n"
	.string "Bug types.\p"
	.string "But, it's weak against Water-type\n"
	.string "Pokémon.$"

PetalburgCity_PokemonCenter_1F_Text_17BF73:: @ 817BF73
	.string "For example, your Mudkip is a\n"
	.string "Water type.\p"
	.string "It's strong against the Fire type.\p"
	.string "But, it's weak against Grass-type\n"
	.string "and Electric-type Pokémon.$"

PetalburgCity_PokemonCenter_1F_Text_JirachiGuyEarly::
    .string "Hm...\n"
    .string "You're quite well-informed.$"
    .string "Isn't it a bit early for you to\n"
    .string "know the secret saying?\p"
    .string "Well, what matters is you know it.\n"
    .string "Here. Weirdo.$"

PetalburgCity_PokemonCenter_1F_Text_JirachiGuyNormal::
    .string "Oh? You know the secret saying.\n"
    .string "I see, I see.\p"
    .string "Well, allow me to make your wish true.\n"
    .string "A mystery gift from me to you!$"

PetalburgCity_PokemonCenter_1F_Text_RecievedJirachi::
    .string "{PLAYER} recieved Jirachi!$"
