PetalburgCity_Text_16433E:: @ 816433E
	.string "Where has our Wally gone?\p"
	.string "We have to leave for Verdanturf Town\n"
	.string "very soon...$"

PetalburgCity_Text_16438A:: @ 816438A
	.string "Hiya! Are you maybe...\n"
	.string "A rookie Trainer?\p"
	.string "Do you know what Pokémon Trainers\n"
	.string "do when they reach a new town?\p"
	.string "They first check what kind of Gym\n"
	.string "is in the town.$"

PetalburgCity_Text_164426:: @ 8164426
	.string "See? This is Petalburg City's Gym.$"

PetalburgCity_Text_164449:: @ 8164449
	.string "This is the Gym's sign. Look for it\n"
	.string "whenever you're looking for a Gym.$"

PetalburgCity_Text_164490:: @ 8164490
	.string "My face is reflected in the water.\p"
	.string "I sure hope my reflection can breathe\n"
	.string "down there. I sure wouldn't be able to.$"

PetalburgCity_Text_16453F:: @ 816453F
	.string "Let's say you have six Pokémon.\n"
	.string "If you catch another one...\p"
	.string "It is automatically sent to a Storage\n"
	.string "Box over a PC connection.$"

PetalburgCity_Text_1645BB:: @ 81645BB
	.string "PETALBURG CITY POKéMON GYM\n"
	.string "LEADER: NORMAN\l"
	.string "“A man in pursuit of power!”$"

PetalburgCity_Text_164602:: @ 8164602
	.string "PETALBURG CITY\n"
	.string "“Where people mingle with nature.”$"

PetalburgCity_Text_164634:: @ 8164634
	.string "WALLY'S HOUSE$"
