PacifidlogTown_Text_16CFC5:: @ 816CFC5
	.string "The sea between Pacifidlog and\n"
	.string "Slateport has a fast-running tide.\p"
	.string "If you decide to Surf, you could end\n"
	.string "up swept away somewhere else.$"

PacifidlogTown_Text_16D04A:: @ 816D04A
	.string "See, isn't it neat?\n"
	.string "These houses are on water!\p"
	.string "I was born here!$"

PacifidlogTown_Text_16D08A:: @ 816D08A
	.string "The folks of Pacifidlog all fish and\n"
	.string "dive as part of the lifestyle.$"

PacifidlogTown_Text_16D0CE:: @ 816D0CE
	.string "PACIFIDLOG TOWN\p"
	.string "“Where the morning sun smiles upon\n"
	.string "the waters.”$"
