Route114_Text_170154:: @ 8170154
	.string "All my POKéMON does is ROAR...\n"
	.string "No one dares to come near me...\p"
	.string "Sigh... If you would, please take\n"
	.string "this TM away...$"

Route114_Text_1701C5:: @ 81701C5
	.string "TM05 contains ROAR.\n"
	.string "A ROAR sends POKéMON scurrying.$"

Route114_Text_1701F9:: @ 81701F9
	.string "Bow! Bowwow!$"

Route114_Text_170206:: @ 8170206
	.string "METEOR FALLS\n"
	.string "RUSTBORO CITY THROUGH HERE$"

Route114_Text_17022E:: @ 817022E
	.string "FOSSIL MANIAC'S HOUSE\n"
	.string "“Fossils gratefully accepted!”$"

Route114_Text_170263:: @ 8170263
	.string "LANETTE'S HOUSE$"

Route114_Text_StoneManiacIntro::
    .string "Oh! Uh...\n"
    .string "Hi there!\p"
    .string "I'm the Stone Maniac.\n"
    .string "I have all sorts of rare stones.\p"
    .string "But the stones I most want are\n"
    .string "the fabled Star Pieces...$"

Route114_Text_StoneManiacHavePiece::
    .string "Oh! That sparkle! You have a\n"
    .string "Star Piece, don't you?\p"
    .string "You must trade it for one of my\n"
    .string "stones! You simply must! Take one!$"

Route114_Text_StoneManiacCancel::
    .string "No! Please! Come back!$"

Route114_Text_StoneManiacConfirm::
	.string "You want the {STR_VAR_1}?$"

Route114_Text_StoneManiacTakeStarPiece::
	.string "{PLAYER} handed over one Star Piece\n"
	.string "in exchange.$"
