MossdeepCity_PokemonCenter_1F_Text_18D62F:: @ 818D62F
	.string "The Gym Leaders in this town were a\n"
	.string "formidable duo.\p"
	.string "Their combination attacks were, like,\n"
	.string "excellent and wow!\p"
    .string "Ever since Tate went on his journey,\n"
    .string "watching them hasn't been the same...$"

MossdeepCity_PokemonCenter_1F_Text_18D69A:: @ 818D69A
	.string "Depending on the special abilities of\n"
	.string "Pokémon, some moves might change\l"
	.string "or not work at all.$"
