Route116_TunnelersRestHouse_Text_192F33:: @ 8192F33
	.string "That Rusturf Tunnel there...\p"
	.string "At first, we had a huge work crew boring\n"
	.string "through rock with the latest machinery.\l"
	.string "But, we had to stop.\p"
	.string "It turns out that we would have had\n"
	.string "a negative effect on wild Pokémon in\l"
	.string "the area.\p"
	.string "So, we've got nothing to do but loll\n"
	.string "around here doing nothing.$"

Route116_TunnelersRestHouse_Text_193049:: @ 8193049
	.string "There's a man digging his way to\n"
	.string "Verdanturf all by his lonesome.\l"
	.string "He's desperate to get through.\p"
	.string "He says that if he digs little by little\n"
	.string "without using machines, he won't\l"
	.string "disturb Pokémon, and he'll avoid harming\l"
	.string "the natural environment.$"

Route116_TunnelersRestHouse_Text_193135:: @ 8193135
	.string "To get to Verdanturf without using\n"
	.string "this Tunnel, you'd have to cross the\l"
	.string "sea to Dewford, sail on to Slateport,\l"
	.string "then travel through Mauville.$"

Route116_TunnelersRestHouse_Text_1931C1:: @ 81931C1
	.string "Did you hear? The Tunnel to Verdanturf\n"
	.string "has gone through!\p"
	.string "Sometimes, if you hope strongly enough,\n"
	.string "dreams do come true.$"
