MeteorFalls_1F_1R_Text_193237:: @ 8193237
	.string "Hehehe!\p"
	.string "With this Meteorite, Mt. Chimney\n"
	.string "will...$"

MeteorFalls_1F_1R_Text_193268:: @ 8193268
	.string "Heh?\p"
	.string "I don't know who you are, but if you get\n"
	.string "in the way of Team Aqua, don't\l"
	.string "expect any mercy!$"

MeteorFalls_1F_1R_Text_1932C5:: @ 81932C5
	.string "Hold it right there, Team Aqua!\p"
    .string "You're badly mistaken if you think you\n"
    .string "can have your way with the world!$"

MeteorFalls_1F_1R_Text_193320:: @ 8193320
	.string "Hehehe!\n"
	.string "Even Team Magma joins us!\p"
	.string "But it's too much trouble to deal with\n"
	.string "you all...\p"
	.string "Heh, it doesn't matter!\p"
	.string "We've got the Meteorite, so off to\n"
	.string "Mt. Chimney we go!\p"
	.string "Hehehe! Be seeing you, you Team\n"
	.string "Magma dingbats!$"

MeteorFalls_1F_1R_Text_1933EC:: @ 81933EC
    .string "MAXIE: Aren't you the child that\n"
    .string "interfered with us at Slateport?\p"
    .string "Ah, so your name is {PLAYER}.\p"
    .string "At the time, I figured you were\n"
    .string "aligned with Team Aqua...\p"
    .string "What a strange child...\p"
    .string "Team Aqua is a dangerous cult\n"
    .string "of deluded fanatics.\p"
    .string "They engage in wanton destruction,\n"
    .string "seeking to expand the sea.\p"
    .string "They are, of course, the mortal\n"
    .string "enemies of the glorious Team Magma.$"

MeteorFalls_1F_1R_Text_193720:: @ 8193720
	.string "Maxie, we should give chase to\n"
	.string "Team Aqua...$"

MeteorFalls_1F_1R_Text_193747:: @ 8193747
	.string "MAXIE: Yes, yes, we must!\n"
	.string "We've got to hurry.\p"
	.string "There's no telling what Team Aqua\n"
	.string "will do at Mt. Chimney!$"

MeteorFalls_1F_1R_Text_1937AA:: @ 81937AA
	.string "MAXIE: {PLAYER}{KUN}, you should keep\n"
	.string "an eye out for Team Aqua, too.\p"
	.string "Farewell!$"

MeteorFalls_1F_1R_Text_1937EB:: @ 81937EB
	.string "I... I'm Cozmo...\n"
	.string "I'm a Professor...\p"
	.string "I usually study Meteorites in\n"
	.string "Fallarbor Town...\p"
	.string "Then some people from Team Aqua\n"
	.string "made me guide them to Meteor Falls...\p"
	.string "They promised me that they would\n"
	.string "excavate Meteorites for me...\p"
	.string "But, I...\n"
	.string "Team Aqua tricked me...\p"
	.string "Oh... That Meteorite...\n"
	.string "It will never be mine now...\p"
	.string "But that Team Aqua...\p"
	.string "What are they going to do with that\n"
	.string "Meteorite at Mt. Chimney?$"

MeteorFalls_1F_1R_Text_19396A:: @ 819396A
	.string "PROF. COZMO: That Team Aqua...\p"
	.string "What are they going to do with that\n"
	.string "Meteorite at Mt. Chimney?$"
