BattleTower_Lobby_Text_199F2C:: @ 8199F2C
	.string "Welcome to the Battle Tower!\p"
	.string "Please register with me to enter\n"
	.string "a Battle Room.$"

BattleTower_Lobby_Text_199F79:: @ 8199F79
	.string "Would you like to make a Battle Room\n"
	.string "challenge?$"

BattleTower_Lobby_Text_199FA9:: @ 8199FA9
	.string "We'll be looking forward to your\n"
	.string "next challenge.$"

BattleTower_Lobby_Text_199FDA:: @ 8199FDA
	.string "Before entering a Battle Room, your\n"
	.string "progress must be saved. Is that okay?$"

BattleTower_Lobby_Text_19A024:: @ 819A024
	.string "There are two Battle Rooms,\n"
	.string "Level 50 and Level 100.\l"
	.string "Which would you like to challenge?$"

BattleTower_Lobby_Text_19A07B:: @ 819A07B
	.string "Please select the Pokémon you wish\n"
	.string "to enter.$"

BattleTower_Lobby_Text_19A0A8:: @ 819A0A8
	.string "I'll direct you to your Battle Room now.$"

BattleTower_Lobby_Text_19A0D1:: @ 819A0D1
	.string "The Battle Tower is a facility made\n"
	.string "especially for Pokémon battles.\p"
	.string "Within the Tower are many Battle Rooms.\p"
	.string "In each Battle Room, seven Trainers\n"
	.string "await your challenge.\p"
	.string "Beat all seven, and you will be rewarded\n"
	.string "with a fabulous prize.\p"
	.string "You may also take a break from your\n"
	.string "challenge by saving your progress.\p"
	.string "Make sure you save properly or you\n"
	.string "won't be able to resume your challenge.$"

BattleTower_Lobby_Text_19A249:: @ 819A249
	.string "Excuse me!\p"
	.string "You don't have three eligible Pokémon.\p"
	.string "You must have three different Pokémon\n"
	.string "of Level 50 or less to enter.\p"
	.string "They also must be holding different\n"
	.string "kinds of items.\p"
	.string "Eggs{STR_VAR_1} ineligible.\p"
	.string "Please come see me when you are ready.$"

BattleTower_Lobby_Text_19A32D:: @ 819A32D
	.string "Excuse me!\p"
	.string "You don't have three eligible Pokémon.\p"
	.string "You must have three different Pokémon\n"
	.string "to enter.\p"
	.string "They also must be holding different\n"
	.string "kinds of items.\p"
	.string "Eggs{STR_VAR_1} ineligible.\p"
	.string "Please come see me when you are ready.$"

BattleTower_Lobby_Text_19A3FD:: @ 819A3FD
	.string "Excuse me!\p"
	.string "You didn't save before you quit your\n"
	.string "challenge last time.\p"
	.string "Because of that, your challenge so far\n"
	.string "has been disqualified. Sorry!$"

BattleTower_Lobby_Text_19A487:: @ 819A487
	.string "Congratulations!\n"
	.string "You've beaten all seven Trainers!\p"
	.string "$"

BattleTower_Lobby_Text_19A4BB:: @ 819A4BB
	.string "For beating seven Trainers in a row,\n"
	.string "you have earned this fabulous prize!\p"
	.string "$"

BattleTower_Lobby_Text_19A506:: @ 819A506
	.string "{PLAYER} received the prize\n"
	.string "{STR_VAR_1}.$"

BattleTower_Lobby_Text_19A520:: @ 819A520
	.string "Oh, your Bag appears to be full.\p"
	.string "Please make room in your Bag, then come\n"
	.string "see me.$"

BattleTower_Lobby_Text_19A571:: @ 819A571
	.string "Thank you for playing!\p"
	.string "$"

BattleTower_Lobby_Text_19A589:: @ 819A589
	.string "Your record will be saved.\n"
	.string "Please wait.$"

BattleTower_Lobby_Text_19A5B1:: @ 819A5B1
	.string "We've been waiting for you!\p"
	.string "$"

BattleTower_Lobby_Text_19A5CE:: @ 819A5CE
	.string "Before entering a Battle Room, your\n"
	.string "progress will be saved. Please wait.$"

BattleTower_Lobby_Text_19A617:: @ 819A617
	.string "You're finally about to face the\n"
	.string "50th Trainer.\p"
	.string "From here on, every time you beat seven\n"
	.string "Trainers in a row, your Pokémon will\l"
	.string "receive a commemorative Ribbon.\p"
	.string "Good luck!$"

BattleTower_Lobby_Text_19A6BE:: @ 819A6BE
	.string "Here are some Ribbons for beating\n"
	.string "seven tough Trainers in a row.\p"
	.string "{PLAYER} received some Ribbons!$"

BattleTower_Lobby_Text_19A719:: @ 819A719
	.string "{PLAYER} put the Ribbons on the\n"
	.string "challenger Pokémon.$"

BattleTower_Lobby_Text_19A747:: @ 819A747
	.string "Hello, hello!\n"
	.string "You're going to battle here, right?\p"
	.string "Can you tell me what's going through\n"
	.string "your mind as you prepare for battle?$"

BattleTower_Lobby_Text_19A7C3:: @ 819A7C3
	.string "Oh, wow, you'll tell me?\n"
	.string "Great! Then, what's your answer?$"

BattleTower_Lobby_Text_19A7FD:: @ 819A7FD
	.string "Oh, so you don't think much about it?\n"
	.string "You're one cool customer.$"

BattleTower_Lobby_Text_19A83D:: @ 819A83D
	.string "Hunh? You changed your mind?\n"
	.string "I guess you're fickle.$"

BattleTower_Lobby_Text_19A871:: @ 819A871
	.string "Okay, so that's how you feel?\n"
	.string "That's quite original.\p"
	.string "Thanks!$"

BattleTower_Lobby_Text_19A8AE:: @ 819A8AE
	.string "The number of matches you win in a row\n"
	.string "is recorded.\p"
	.string "The record is posted beside the\n"
	.string "registration counter.\p"
	.string "It's also on the back of your\n"
	.string "Trainer Card.$"

BattleTower_Lobby_Text_19A946:: @ 819A946
	.string "Once you've entered the Battle Tower,\n"
	.string "you can't leave until you either lose\l"
	.string "or you beat seven Trainers in a row.\p"
	.string "You'd best be certain that you're up\n"
	.string "to the challenge.$"

BattleTower_Lobby_Text_19A9EE:: @ 819A9EE
	.string "Hahahaha! Pure magnificence!\n"
	.string "Pure magnificence indeed!\p"
	.string "Do you realize what you've achieved?\n"
	.string "You've beaten 50 Trainers in a row!\p"
	.string "Yes, purely magnificent!\p"
	.string "As the Owner of the Battle Tower,\n"
	.string "let me give you a memento!$"

BattleTower_Lobby_Text_19AAC4:: @ 819AAC4
	.string "Wahahaha! Pure magnificence!\n"
	.string "Absolutely pure magnificence indeed!\p"
	.string "Do you realize what you've achieved?\n"
	.string "You've beaten 100 Trainers in a row!\p"
	.string "Yes, absolutely magnificent!\p"
	.string "As the Owner of the Battle Tower,\n"
	.string "let me give you a memento!$"

BattleTower_Lobby_Text_19ABAA:: @ 819ABAA
	.string "I suggest you keep it displayed.\n"
	.string "It will surely attract attention.$"

BattleTower_Lobby_Text_19ABED:: @ 819ABED
	.string "Oh?\n"
	.string "Your PC has no room for this...\p"
	.string "But it would be a shame to waste this...\n"
	.string "Please come back for this!$"

BattleTower_Lobby_Text_19AC55:: @ 819AC55
	.string "I'm overwhelmed with satisfaction after\n"
	.string "seeing your magnificent performance.\p"
	.string "It makes the building of the Battle\n"
	.string "Tower all worthwhile!$"
