PetalburgCity_Gym_Text_179DF6:: @ 8179DF6
	.string "DAD: Hm?\p"
	.string "Well, if it isn't {PLAYER}!\n"
	.string "So you're all finished moving in?\p"
	.string "I'm surprised that you managed to\n"
	.string "get here by yourself.\p"
	.string "Oh, I see.\n"
	.string "You're with your Pokémon.\p"
	.string "Hm... Then I guess you're going to\n"
	.string "become a Trainer like me, {PLAYER}.\p"
	.string "That's great news!\n"
	.string "I'll be looking forward to it!$"

PetalburgCity_Gym_Text_179F07:: @ 8179F07
	.string "Um... I... I'd like to get a\n"
	.string "Pokémon, please...$"

PetalburgCity_Gym_Text_179F37:: @ 8179F37
	.string "DAD: Hm? You're... Uh... Oh, right.\n"
	.string "You're Wally, right?$"

PetalburgCity_Gym_Text_179F70:: @ 8179F70
	.string "WALLY: I'm going to go stay with my\n"
	.string "relatives in Verdanturf Town.\p"
	.string "I thought I would be lonely by myself,\n"
	.string "so I wanted to take a Pokémon along.\p"
	.string "But I've never caught a Pokémon before.\n"
	.string "I don't know how...$"

PetalburgCity_Gym_Text_17A03A:: @ 817A03A
	.string "DAD: Hm. I see.$"

PetalburgCity_Gym_Text_17A04A:: @ 817A04A
	.string "DAD: {PLAYER}, you heard that,\n"
	.string "right?\p"
	.string "Go with Wally and make sure that he\n"
	.string "safely catches a Pokémon.$"

PetalburgCity_Gym_Text_17A0A8:: @ 817A0A8
	.string "Wally, here, I'll loan you my Pokémon.\p"
	.string "Wally received a Zigzagoon!$"

PetalburgCity_Gym_Text_17A0EB:: @ 817A0EB
	.string "WALLY: Oh, wow!\n"
	.string "A Pokémon!\p"
	.string "DAD: Hm. I'll give you a Poké Ball, too.\n"
	.string "Go for it!\p"
	.string "Wally received a Poké Ball!$"

PetalburgCity_Gym_Text_17A156:: @ 817A156
	.string "WALLY: Oh, wow!\n"
	.string "Thank you!$"

PetalburgCity_Gym_Text_17A171:: @ 817A171
	.string "{PLAYER}... Would you really come\n"
	.string "with me?$"

PetalburgCity_Gym_Text_17A196:: @ 817A196
	.string "DAD: So, did it work out?$"

PetalburgCity_Gym_Text_17A1B0:: @ 817A1B0
	.string "WALLY: Thank you, yes, it did.\n"
	.string "Here's your Pokémon back.\p"
	.string "{PLAYER}, thank you for coming along\n"
	.string "with me.\p"
	.string "You two are why I was able to catch\n"
	.string "my Pokémon.\p"
	.string "I promise I'll take really good\n"
	.string "care of it.\p"
	.string "Oh! My mom's waiting for me, so I\n"
	.string "have to go!\p"
	.string "Bye, {PLAYER}!$"

PetalburgCity_Gym_Text_17A2A4:: @ 817A2A4
	.string "DAD: Now...\p"
	.string "{PLAYER}, if you want to become a\n"
	.string "strong Trainer, here's my advice.\p"
	.string "Head for Rustboro City beyond this\n"
	.string "town.\p"
	.string "There, you should challenge the Gym\n"
	.string "Leader, Roxanne.\p"
	.string "After her, go on to other Pokémon\n"
	.string "Gyms and defeat their Leaders.\p"
	.string "Collect Badges from them,\n"
	.string "understood?\p"
	.string "Of course, I'm a Gym Leader, too.\n"
	.string "We'll battle one day, {PLAYER}.\p"
	.string "But that's only after you become\n"
	.string "stronger, {PLAYER}.$"

PetalburgCity_Gym_Text_17A41E:: @ 817A41E
	.string "DAD: Hm? Aren't you going to the\n"
	.string "Pokémon Gym in Rustboro City?\p"
	.string "There's no challenge for me to\n"
	.string "battle a greenhorn Trainer.\p"
	.string "{PLAYER}, I want you to challenge me\n"
	.string "when you become a lot stronger.\p"
	.string "I'll battle you, {PLAYER}, when you\n"
	.string "can show me four Gym Badges, okay?$"

PetalburgCity_Gym_Text_17A518:: @ 817A518
	.string "DAD: I see... So, you've beaten the\n"
	.string "Gym Leader in Rustboro City.\p"
	.string "But there are many more Trainers\n"
	.string "who are stronger than you, {PLAYER}.\p"
	.string "Across the sea in Dewford Town is a\n"
	.string "Gym Leader named Brawly.\p"
	.string "You should go challenge him.$"

PetalburgCity_Gym_Text_17A5F3:: @ 817A5F3
	.string "DAD: Hm... {PLAYER}, you have gotten\n"
	.string "stronger.\p"
	.string "I can tell by the number of Badges\n"
	.string "that you've earned.$"

PetalburgCity_Gym_Text_17A653:: @ 817A653
	.string "DAD: Hm...\n"
	.string "So, you did get four Gym Badges.\p"
	.string "Fine, as I promised, we will have a\n"
	.string "Pokémon battle.\p"
	.string "{PLAYER}...\p"
	.string "I'm so happy that I can have a \n"
	.string "real battle with my own child.\p"
	.string "But, a battle is a battle!\p"
	.string "I will do everything in my power as\n"
	.string "a Gym Leader to win.\p"
	.string "{PLAYER}, you'd better give it your\n"
	.string "best shot, too!$"

PetalburgCity_Gym_Text_17A77A:: @ 817A77A
	.string "...\p"
	.string "I... I can't...\p"
	.string "I can't believe it. {PLAYER}...\p"
	.string "I lost to {PLAYER}?\p"
	.string "But, rules are rules!\n"
	.string "Here, take this.$"

PetalburgCity_Gym_Text_17A7DD:: @ 817A7DD
	.string "{PLAYER} received the Balance Badge\n"
	.string "from Dad!$"

PetalburgCity_Gym_Text_17A805:: @ 817A805
	.string "DAD: With that Badge, the Defense\n"
	.string "of all your Pokémon will increase.\p"
	.string "Pokémon that know the HM move Surf\n"
	.string "will be able to travel over water.\p"
	.string "This is my gift to you. {PLAYER}, I'm\n"
	.string "sure you can use it correctly.$"

PetalburgCity_Gym_Text_17A8CF:: @ 817A8CF
	.string "DAD: TM15 contains Hyper Beam.\p"
	.string "It's strong, but it requires a\n"
	.string "turn to recharge after using.\p"
	.string "Take care you don't throw away\n"
	.string "a good situation with it.$"

PetalburgCity_Gym_Text_17A976:: @ 817A976
	.string "DAD: As the Gym Leader, I can't\n"
	.string "express how upset I am...\p"
	.string "But as a father, it makes me both\n"
	.string "happy and a little sad. It's odd...$"

PetalburgCity_Gym_Text_17A9F6:: @ 817A9F6
	.string "DAD: Oh, yes...\p"
	.string "Wally's parents came calling\n"
	.string "earlier.\p"
	.string "They said that they had something\n"
	.string "they wanted to give you, {PLAYER}.$"

PetalburgCity_Gym_Text_17AA6B:: @ 817AA6B
	.string "DAD: {PLAYER}, you should go visit\n"
	.string "your mother every so often.\p"
	.string "I'm going to stay here and redouble\n"
	.string "my training.\p"
	.string "It would bother me as a Trainer to\n"
	.string "not avenge my loss to you, {PLAYER}!$"

PetalburgCity_Gym_Text_17AB17:: @ 817AB17
	.string "DAD: {PLAYER}, how are things going?\p"
	.string "The world of Pokémon is deep.\p"
	.string "I honestly think that no amount of\n"
	.string "training would ever be enough.$"

PetalburgCity_Gym_Text_17AB96:: @ 817AB96
	.string "Hey, how's it going, Champion-\n"
	.string "bound {PLAYER}?\p"
	.string "The doors in this Gym open when you\n"
	.string "beat the awaiting Trainers.\p"
	.string "Whoops! The doors in this room are\n"
	.string "already open, so don't attack me!\p"
	.string "The Trainers of Petalburg Gym use\n"
	.string "all kinds of items.\p"
	.string "The door at the left leads to the\n"
	.string "Speed Room.\p"
	.string "The door at the right leads to the\n"
	.string "Accuracy Room.\p"
	.string "The room's name will be on the\n"
	.string "door, so choose carefully.\p"
	.string "Once you've chosen the door...\n"
	.string "Well, hey, go for it!$"

PetalburgCity_Gym_Text_17AD49:: @ 817AD49
	.string "{PLAYER}! Whoa! You've overcome even\n"
	.string "your own father!\p"
	.string "Like, whoa!\n"
	.string "What a stunning turn of events!$"

PetalburgCity_Gym_Text_17ADA5:: @ 817ADA5
	.string "The ability to attack before the\n"
	.string "opponent...\p"
	.string "Just that alone puts me at a great\n"
	.string "advantage, don't you agree?$"

PetalburgCity_Gym_Text_17AE11:: @ 817AE11
	.string "That was a magnificent battle!$"

PetalburgCity_Gym_Text_17AE30:: @ 817AE30
	.string "Go on to the next room where a new\n"
	.string "challenge awaits you.\p"
	.string "At the left is the Ailment\n"
	.string "Room.\p"
	.string "The right door leads to the Defense\n"
	.string "Room.$"

PetalburgCity_Gym_Text_17AEBB:: @ 817AEBB
	.string "Whomever you beat, and whomever you\n"
	.string "may lose to, you never shirk from\l"
	.string "training yourself and your Pokémon.\p"
	.string "That's what I think being a\n"
	.string "Gym Leader is all about.$"

PetalburgCity_Gym_Text_17AF5A:: @ 817AF5A
	.string "Winning isn't just about\n"
	.string "doing the most straight damage!$"

PetalburgCity_Gym_Text_17AF98:: @ 817AF98
	.string "My Pokémon took too much damage...$"

PetalburgCity_Gym_Text_17AFD3:: @ 817AFD3
	.string "The next room is the Strength Room.\n"
	.string "Can you withstand brute force?$"

PetalburgCity_Gym_Text_17B016:: @ 817B016
	.string "After you beat our Leader, the\n"
	.string "training has become a lot tougher.$"

PetalburgCity_Gym_Text_17B058:: @ 817B058
	.string "Just when you think you're going to\n"
	.string "win, your opponent restores HP...\p"
	.string "Can you just imagine how awful that\n"
	.string "must feel?\p"
	.string "I'll show you exactly how awful it\n"
	.string "feels!$"

PetalburgCity_Gym_Text_17B0F7:: @ 817B0F7
	.string "I couldn't restore HP enough...\n"
	.string "What Attack power...$"

PetalburgCity_Gym_Text_17B12C:: @ 817B12C
	.string "I should have expected no less from\n"
	.string "our Leader's kid.\p"
	.string "No, wait! A Trainer's abilities are\n"
	.string "earned only through effort.\p"
	.string "I lost because my own efforts\n"
	.string "weren't enough.\p"
	.string "Go on! The One-Hit KO Room is next.$"

PetalburgCity_Gym_Text_17B1F4:: @ 817B1F4
	.string "I'm going to keep training at Gyms.\n"
	.string "One day, I'll become a Leader.$"

PetalburgCity_Gym_Text_17B237:: @ 817B237
	.string "I'm not going to take it easy just\n"
	.string "because you're our Leader's kid.\p"
	.string "I'll show you how horrid it is for\n"
	.string "a Pokémon to take a critical hit!$"

PetalburgCity_Gym_Text_17B2C0:: @ 817B2C0
	.string "Your power...\n"
	.string "You're the real deal.$"

PetalburgCity_Gym_Text_17B2E4:: @ 817B2E4
	.string "Your father really is strong. He's\n"
	.string "a Trainer worth my respect.\p"
	.string "And, I sense the same glow coming\n"
	.string "from you as your father.\p"
	.string "I hope that you'll stage a terrific\n"
	.string "battle with your father!$"

PetalburgCity_Gym_Text_17B39B:: @ 817B39B
	.string "Since your dad became the Leader,\n"
	.string "the Trainers of Petalburg City have\l"
	.string "become a lot tougher.$"

PetalburgCity_Gym_Text_17B3F7:: @ 817B3F7
	.string "Giggle...\n"
	.string "This is the Evasion Room.\p"
	.string "It's pretty nasty when none of\n"
	.string "your attacks ever connect.$"

PetalburgCity_Gym_Text_17B454:: @ 817B454
	.string "You were a cut above me...$"

PetalburgCity_Gym_Text_17B46F:: @ 817B46F
	.string "There are some even stronger\n"
	.string "Trainers waiting for you.\p"
	.string "The left is the Defense Room, and\n"
	.string "the right is the Recovery Room.\p"
	.string "Your Pokémon's Attack power will be\n"
	.string "on trial either way.$"

PetalburgCity_Gym_Text_17B521:: @ 817B521
	.string "Do you know what we're trying to\n"
	.string "achieve as Trainers?\p"
	.string "We're striving to become soul mates\n"
	.string "with our Pokémon.$"

PetalburgCity_Gym_Text_17B58D:: @ 817B58D
	.string "The higher the Defense, the more\n"
	.string "reckless I can be in attack.$"

PetalburgCity_Gym_Text_17B5CB:: @ 817B5CB
	.string "Our Defenses weren't enough...$"

PetalburgCity_Gym_Text_17B5EA:: @ 817B5EA
	.string "I think you've taught me a valuable\n"
	.string "lesson here.\p"
	.string "Now, go on! The left door goes to\n"
	.string "the Strength Room.\p"
	.string "The right door opens to the\n"
	.string "One-Hit KO Room.\p"
	.string "Both of them have Trainers who are\n"
	.string "offensively skilled.$"

PetalburgCity_Gym_Text_17B6B5:: @ 817B6B5
	.string "Hi! Have you tried using Surf?$"

PetalburgCity_Gym_Text_17B6D4:: @ 817B6D4
	.string "Our Gym Leader told us to go all out\n"
	.string "and beat you.\p"
	.string "Even if you happen to be the\n"
	.string "Leader's kid!$"

PetalburgCity_Gym_Text_17B732:: @ 817B732
	.string "But... I went all out!$"

PetalburgCity_Gym_Text_17B749:: @ 817B749
	.string "The way you use your Pokémon...\n"
	.string "It's like your father's style.\p"
	.string "Go on through! The Gym Leader, your\n"
	.string "father, is waiting!$"

PetalburgCity_Gym_Text_17B7C0:: @ 817B7C0
	.string "Sure, it's fine to make your Pokémon\n"
	.string "stronger.\p"
	.string "But what decides the winner?\p"
	.string "Why, it's the feelings Trainers have for\n"
	.string "their Pokémon.$"

PetalburgCity_Gym_Text_17B844:: @ 817B844
	.string "This door appears to be locked\n"
	.string "right now...$"

PetalburgCity_Gym_Text_17B870:: @ 817B870
	.string "“Speed Room,” the sign says.\p"
	.string "Do you want to go through?$"

UnknownString_817B8A8: @ 817B8A8
	.string "This door appears to be locked\n"
	.string "right now...$"

PetalburgCity_Gym_Text_17B8D4:: @ 817B8D4
	.string "“Evasion Room,” the sign says.\p"
	.string "Do you want to go through?$"

PetalburgCity_Gym_Text_17B90F:: @ 817B90F
	.string "“Ailment Room,” the sign\n"
	.string "says.\p"
	.string "Do you want to go through?$"

PetalburgCity_Gym_Text_17B950:: @ 817B950
	.string "“Defense Room,” the sign says.\p"
	.string "Do you want to go through?$"

PetalburgCity_Gym_Text_17B98A:: @ 817B98A
	.string "“Recovery Room,” the sign says.\p"
	.string "Do you want to go through?$"

PetalburgCity_Gym_Text_17B9C5:: @ 817B9C5
	.string "“Strength Room,” the sign says.\p"
	.string "Do you want to go through?$"

PetalburgCity_Gym_Text_17BA00:: @ 817BA00
	.string "“One-Hit KO Room,” the sign says.\p"
	.string "Do you want to go through?$"

PetalburgCity_Gym_Text_17BA3D:: @ 817BA3D
	.string "“Gym Leader's Room\p"
	.string "“See for yourself what Pokémon await\n"
	.string "you!” the sign says.\p"
	.string "Do you want to go through?$"

PetalburgCity_Gym_Text_17BAA5:: @ 817BAA5
	.string "PETALBURG CITY POKéMON GYM$"

PetalburgCity_Gym_Text_17BAC0:: @ 817BAC0
	.string "PETALBURG CITY POKéMON GYM\p"
	.string "NORMAN'S CERTIFIED TRAINERS:\n"
	.string "{PLAYER}$"
