Route110_TrickHousePuzzle5_Text_19D423:: @ 819D423
	.string "CLICKETY-CLACK...\n"
	.string "MECHADOLL 1 AM I!\p"
	.string "IF YOU ANSWER QUIZZES CORRECTLY,\n"
	.string "THEN YOU WILL GO TO MECHADOLL 5.\l"
	.string "THEN YOU CAN OBTAIN THE SECRET CODE.$"

Route110_TrickHousePuzzle5_Text_19D4AE:: @ 819D4AE
	.string "MECHADOLL 1 QUIZ.\p"
	.string "One of these Pokémon was kidnapped\n"
	.string "at Rusturf Tunnel. Which one is it?$"

Route110_TrickHousePuzzle5_Text_19D501:: @ 819D501
	.string "MECHADOLL 1 QUIZ.\p"
	.string "One of these Pokémon cannot learn the\n"
	.string "move Overheat. Which one is it?$"

Route110_TrickHousePuzzle5_Text_19D553:: @ 819D553
	.string "MECHADOLL 1 QUIZ.\p"
	.string "One of these Pokémon is susceptible to\n"
	.string "the move Surf. Which one is it?$"

Route110_TrickHousePuzzle5_Text_19D599:: @ 819D599
	.string "CONGRATULATIONS. CORRECT YOU ARE.\n"
	.string "GO THROUGH. PLEASE.$"

Route110_TrickHousePuzzle5_Text_19D5CF:: @ 819D5CF
	.string "BZZZT. DISAPPOINTMENT.\n"
	.string "ERROR.$"

Route110_TrickHousePuzzle5_Text_19D5ED:: @ 819D5ED
	.string "WAHAHAHAHA! WAHAHAHAHA!\n"
	.string "CLICKETY-CLACK!$"

Route110_TrickHousePuzzle5_Text_19D615:: @ 819D615
	.string "YOUR NEXT CHALLENGE WE WAIT FOR.$"

Route110_TrickHousePuzzle5_Text_19D636:: @ 819D636
	.string "CLICKETY-CLACK...\n"
	.string "MECHADOLL 2 AM I!\p"
	.string "MECHADOLL 1'S QUIZ DIFFICULTY LEVEL\n"
	.string "IS SET TOO LOW.$"

Route110_TrickHousePuzzle5_Text_19D68E:: @ 819D68E
	.string "MECHADOLL 2 QUIZ.\p"
	.string "Pokémon are sold at the Mauville Game\n"
	.string "Corner. Which of these is not for sale?$"

Route110_TrickHousePuzzle5_Text_19D6EC:: @ 819D6EC
	.string "MECHADOLL 2 QUIZ.\p"
	.string "Which of these Pokémon did Brawly\n"
	.string "use in the Dewford Gym?$"

Route110_TrickHousePuzzle5_Text_19D745:: @ 819D745
	.string "MECHADOLL 2 QUIZ.\p"
	.string "Which of these moves can you purchase\n"
	.string "a TM for in Slateport City?$"

UnknownString_819D79D: @ 819D79D
	.string "CONGRATULATIONS. CORRECT YOU ARE.\n"
	.string "GO THROUGH. PLEASE.$"

Route110_TrickHousePuzzle5_Text_19D7D3:: @ 819D7D3
	.string "CLICKETY-CLACK...\n"
	.string "MECHADOLL 3 AM I!\p"
	.string "MATTERS OF MONEY ARE MY SOLE FOCUS.$"

Route110_TrickHousePuzzle5_Text_19D81B:: @ 819D81B
	.string "MECHADOLL 3 QUIZ.\p"
	.string "Which costs more? Twenty Burn Heals\n"
	.string "or twelve Potions and a Full Heal?$"

Route110_TrickHousePuzzle5_Text_19D865:: @ 819D865
	.string "MECHADOLL 3 QUIZ.\p"
	.string "How much money would be spent buying\n"
	.string "the Coins to exchange for a Pikachu?$"

Route110_TrickHousePuzzle5_Text_19D8BA:: @ 819D8BA
	.string "MECHADOLL 3 QUIZ.\p"
	.string "Sell seven Poké Balls and buy one\n"
	.string "Antidote. How much money remains?$"

UnknownString_819D907: @ 819D907
	.string "CONGRATULATIONS. CORRECT YOU ARE.\n"
	.string "GO THROUGH. PLEASE.$"

Route110_TrickHousePuzzle5_Text_19D93D:: @ 819D93D
	.string "CLICKETY-CLACK...\n"
	.string "MECHADOLL 4 THAT IS ME!\p"
	.string "MY QUIZ TESTS POKéMON KNOWLEDGE.$"

Route110_TrickHousePuzzle5_Text_19D987:: @ 819D987
	.string "MECHADOLL 4 QUIZ.\p"
	.string "Which of these Pokémon could you not\n"
	.string "acquire before your third badge?$"

Route110_TrickHousePuzzle5_Text_19D9DC:: @ 819D9DC
	.string "MECHADOLL 4 QUIZ.\p"
	.string "Which of these is not a real\n"
	.string "Pokémon move?$"

Route110_TrickHousePuzzle5_Text_19DA1D:: @ 819DA1D
	.string "MECHADOLL 4 QUIZ.\p"
	.string "Which of these rooms was a new\n"
	.string "addition to the Petalburg Gym?$"

UnknownString_819DA64: @ 819DA64
	.string "CONGRATULATIONS. CORRECT YOU ARE.\n"
	.string "GO THROUGH. PLEASE.$"

Route110_TrickHousePuzzle5_Text_19DA9A:: @ 819DA9A
	.string "CLICKETY-CLACK...\n"
	.string "MECHADOLL 5 AM I!\p"
	.string "THE MASTER'S BEST AND PROUDEST\n"
	.string "ACHIEVEMENT AM I.$"

Route110_TrickHousePuzzle5_Text_19DAEF:: @ 819DAEF
	.string "MECHADOLL 5 QUIZ.\p"
	.string "How many other Trainers have been\n"
	.string "in Trick House challenges with you?$"

Route110_TrickHousePuzzle5_Text_19DB43:: @ 819DB43
	.string "MECHADOLL 5 QUIZ.\p"
	.string "Which Trick House challenge had\n"
	.string "the most girls in it?$"

Route110_TrickHousePuzzle5_Text_19DB97:: @ 819DB97
	.string "MECHADOLL 5 QUIZ.\p"
	.string "How did the scroll in the last Trick House\n"
	.string "challenge describe the Trick Master?$"

UnknownString_819DBD4: @ 819DBD4
	.string "CONGRATULATIONS. CORRECT YOU ARE.\n"
	.string "GO THROUGH. PLEASE.$"

UnknownString_819DC0A: @ 819DC0A
	.string "{PLAYER} wrote down the secret code\n"
	.string "on the door.\p"
	.string "“Trick Master is my life.”\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "The lock clicked open!$"
