LavaridgeTown_HerbShop_Text_17615C:: @ 817615C
	.string "Welcome to the Herb Shop, home of\n"
	.string "effective and inexpensive medicine!$"

LavaridgeTown_HerbShop_Text_1761A2:: @ 81761A2
	.string "You've come to look at herbal medicine\n"
	.string "in Lavaridge?\p"
	.string "That's rather commendable.\p"
	.string "I like you! Take this!$"

LavaridgeTown_HerbShop_Text_176209:: @ 8176209
	.string "That Charcoal I gave you, it's used\n"
	.string "for making herbal medicine.\p"
	.string "It also does wonders when held by\n"
	.string "a Pokémon.\p"
	.string "It intensifies the power of Fire-type\n"
	.string "moves.$"

LavaridgeTown_HerbShop_Text_1762A3:: @ 81762A3
	.string "Herbal medicine works impressively well.\n"
	.string "But your Pokémon will dislike you for it.\l"
	.string "It must be horribly bitter!$"

LavaridgeTown_HerbShop_Text_Psychiatrist_Intro::
    .string "Welcome to the Herb Shop.\n"
    .string "I am the Pokémon Psychiatrist.\p"
    .string "I can train your Pokémon to overcome\n"
    .string "their natures and adapt their stats.$"

LavaridgeTown_HerbShop_Text_Psychiatrist_ShowPrice::
    .string "My services cost ¥10000.$"

LavaridgeTown_HerbShop_Text_Psychiatrist_WhichMon::
    .string "Which Pokémon needs my training?$"

LavaridgeTown_HerbShop_Text_Psychiatrist_WhichStrength::
    .string "Alright. Which stat do you want\n"
    .string "this Pokémon to focus on?$"

LavaridgeTown_HerbShop_Text_Psychiatrist_WhichWeakness::
    .string "And which stat should be least\n"
    .string "important for this Pokémon?$"

LavaridgeTown_HerbShop_Text_Psychiatrist_Lonely::
    .string "So, focus on Attack at the\n"
    .string "expense of Defense?$"

LavaridgeTown_HerbShop_Text_Psychiatrist_Adamant::
    .string "So, focus on Attack at the\n"
    .string "expense of Sp. Atk?$"

LavaridgeTown_HerbShop_Text_Psychiatrist_Naughty::
    .string "So, focus on Attack at the\n"
    .string "expense of Sp. Def?$"

LavaridgeTown_HerbShop_Text_Psychiatrist_Brave::
    .string "So, focus on Attack at the\n"
    .string "expense of Speed?$"

LavaridgeTown_HerbShop_Text_Psychiatrist_Bold::
    .string "So, focus on Defense at the\n"
    .string "expense of Attack?$"

LavaridgeTown_HerbShop_Text_Psychiatrist_Impish::
    .string "So, focus on Defense at the\n"
    .string "expense of Sp. Atk?$"

LavaridgeTown_HerbShop_Text_Psychiatrist_Lax::
    .string "So, focus on Defense at the\n"
    .string "expense of Sp. Def?$"

LavaridgeTown_HerbShop_Text_Psychiatrist_Relaxed::
    .string "So, focus on Defense at the\n"
    .string "expense of Speed?$"

LavaridgeTown_HerbShop_Text_Psychiatrist_Modest::
    .string "So, focus on Sp. Atk at the\n"
    .string "expense of Attack?$"

LavaridgeTown_HerbShop_Text_Psychiatrist_Mild::
    .string "So, focus on Sp. Atk at the\n"
    .string "expense of Defense?$"

LavaridgeTown_HerbShop_Text_Psychiatrist_Rash::
    .string "So, focus on Sp. Atk at the\n"
    .string "expense of Sp. Def?$"

LavaridgeTown_HerbShop_Text_Psychiatrist_Quiet::
    .string "So, focus on Sp. Atk at the\n"
    .string "expense of Speed?$"

LavaridgeTown_HerbShop_Text_Psychiatrist_Calm::
    .string "So, focus on Sp. Def at the\n"
    .string "expense of Attack?$"

LavaridgeTown_HerbShop_Text_Psychiatrist_Gentle::
    .string "So, focus on Sp. Def at the\n"
    .string "expense of Defense?$"

LavaridgeTown_HerbShop_Text_Psychiatrist_Careful::
    .string "So, focus on Sp. Def at the\n"
    .string "expense of Sp. Atk?$"

LavaridgeTown_HerbShop_Text_Psychiatrist_Sassy::
    .string "So, focus on Sp. Def at the\n"
    .string "expense of Speed?$"

LavaridgeTown_HerbShop_Text_Psychiatrist_Timid::
    .string "So, focus on Speed at the\n"
    .string "expense of Attack?$"

LavaridgeTown_HerbShop_Text_Psychiatrist_Hasty::
    .string "So, focus on Speed at the\n"
    .string "expense of Defense?$"

LavaridgeTown_HerbShop_Text_Psychiatrist_Jolly::
    .string "So, focus on Speed at the\n"
    .string "expense of Sp. Atk?$"

LavaridgeTown_HerbShop_Text_Psychiatrist_Naive::
    .string "So, focus on Speed at the\n"
    .string "expense of Sp. Def?$"

LavaridgeTown_HerbShop_Text_Psychiatrist_Balance::
    .string "So, focus on keeping all\n"
    .string "stats about even?$"

LavaridgeTown_HerbShop_Text_Psychiatrist_Done::
    .string "Alright, I'll get to work.\p"
    .string "... ... ... ... ...\n"
    .string "... ... ... ... ...$"

LavaridgeTown_HerbShop_Text_Psychiatrist_Done2::
    .string "There. That will be ¥10000.$"

LavaridgeTown_HerbShop_Text_Psychiatrist_Redundant::
    .string "Alright, I'll get to work.\p"
    .string "... ... ... ... ...\n"
    .string "... ... ... ... ...\p"
    .string "I'm sorry...this regimen\n"
    .string "wouldn't accomplish anything.$"

LavaridgeTown_HerbShop_Text_Psychiatrist_Egg::
    .string "...This is an egg.\n"
    .string "Very funny.$"

LavaridgeTown_HerbShop_Text_Psychiatrist_Bye::
    .string "Hm. Come back whenever...$"

LavaridgeTown_HerbShop_Text_Psychiatrist_NeedMoney::
    .string "You don't have enough money.$"
