MauvilleCity_House2_Text_18244E:: @ 818244E
	.string "If I had a Bike, it'd be easy to cycle to\n"
	.string "Slateport for some shopping.\p"
	.string "I'd be able to buy Harbor Mail at the\n"
	.string "Pokémon Mart in Slateport...$"

MauvilleCity_House2_Text_1824D8:: @ 81824D8
	.string "Oh! You have Harbor Mail?\n"
	.string "Will you trade it for a Coin Case?$"

MauvilleCity_House2_Text_182515:: @ 8182515
	.string "Oh, I'm so happy!\n"
	.string "Okay, I'll trade you a Coin Case!$"

MauvilleCity_House2_Text_182549:: @ 8182549
	.string "That Coin Case can be used at the\n"
	.string "Game Corner.$"

MauvilleCity_House2_Text_182578:: @ 8182578
	.string "Oh, that's disappointing.\p"
	.string "A Coin Case is needed for the\n"
	.string "Game Corner.$"
