VerdanturfTown_PokemonCenter_1F_Text_17831D:: @ 817831D
	.string "I daresay a Trainer isn't qualified if\n"
	.string "Pokémon aren't settled and friendly.\l"
	.string "Have you given them any {POKEBLOCK}s?$"

VerdanturfTown_PokemonCenter_1F_Text_178389:: @ 8178389
	.string "Let me hazard a guess why you're in\n"
	.string "Verdanturf. The reason: Contests.\p"
	.string "All Contest challenges originate here.$"
