PacifidlogTown_House2_Text_1790C1:: @ 81790C1
	.string "Er-hem!\p"
	.string "I am the Pokémon Fan Club's most\n"
	.string "important person, the Chairman's\l"
	.string "younger brother.\p"
	.string "I'm here enjoying my vacation with\n"
	.string "Pokémon, yes, indeed.$"

PacifidlogTown_House2_Text_179155:: @ 8179155
	.string "Ah!\n"
	.string "Your Pokémon...$"

PacifidlogTown_House2_Text_179169:: @ 8179169
	.string "It clearly likes you very much.\p"
	.string "A Pokémon that adoring and adorable\n"
	.string "deserves an item like this, no?$"

PacifidlogTown_House2_Text_1791CA:: @ 81791CA
	.string "Hmm...\n"
	.string "It's not bad, but it's also not good.\p"
	.string "You, as the Trainer, need to put in\n"
	.string "some more effort.$"

PacifidlogTown_House2_Text_17922D:: @ 817922D
	.string "It has a vicious look to it...\p"
	.string "Treat this Pokémon better!$"

PacifidlogTown_House2_Text_179283:: @ 8179283
	.string "If a Pokémon likes you a lot, Return's\n"
	.string "power is enhanced.$"

PacifidlogTown_House2_Text_1792F2:: @ 81792F2
	.string "Oh, yes. In about {STR_VAR_1} or so days,\n"
	.string "I should be getting a good item or two.\p"
	.string "You should come see me then.\n"
	.string "I'll give you an item that's suitable for\l"
	.string "your Pokémon.$"

PacifidlogTown_House2_Text_17938B:: @ 817938B
	.string "AZURILL: Rurii.$"

PacifidlogTown_House2_Text_17939B:: @ 817939B
	.string "It appears to be very friendly with the\n"
	.string "Trainer.$"

PacifidlogTown_House2_Text_1793CC:: @ 81793CC
	.string "AZURILL: Rururi!$"

PacifidlogTown_House2_Text_1793DD:: @ 81793DD
	.string "It doesn't appear to like the Trainer\n"
	.string "very much.$"
