MossdeepCity_Mart_Text_18D758:: @ 818D758
	.string "Revive is fantastic!\p"
	.string "Give it to a fainted Pokémon, and the\n"
	.string "Pokémon will arise.\p"
	.string "But be careful, Revive doesn't restore\n"
	.string "the used-up PP of moves.$"

MossdeepCity_Mart_Text_18D7E7:: @ 818D7E7
	.string "Max Repel keeps all weak Pokémon away.\p"
	.string "Out of all the Repel sprays, it lasts\n"
	.string "the longest.$"

MossdeepCity_Mart_Text_18D841:: @ 818D841
	.string "The Net and Dive BALLS are rare Poké\n"
	.string "Balls that are only made in Mossdeep.\p"
	.string "A Net Ball is effective against\n"
	.string "Bug-type and Water-type Pokémon.\p"
	.string "A Dive Ball works best on Pokémon at\n"
	.string "the bottom of the sea.$"
