LilycoveCity_DepartmentStore_2F_Text_18C162:: @ 818C162
	.string "Learn to use items properly.\n"
	.string "That's basic, really.$"

LilycoveCity_DepartmentStore_2F_Text_18C195:: @ 818C195
	.string "My husband is waiting at home.\n"
	.string "What would make a good gift for him?$"

LilycoveCity_DepartmentStore_2F_Text_18C1D9:: @ 818C1D9
	.string "I'm leaving on a long journey soon.\n"
	.string "I need to stock up on items.$"

LilycoveCity_DepartmentStore_2F_Text_StairsOutOfOrder::
	.string "Stairs are out of order, sorry.\n"
    .string "No, really, you can't go up now.\p"
    .string "You're a trainer, right? Maybe stop\n"
    .string "by again after beating Fortree's Gym.\p"
    .string "We should have the place fixed up by\n"
    .string "the time you get back.$"

UnknownString_818C21A: @ 818C21A
	.string "FOR YOUR TRAVELING COMPANIONS\n"
	.string "2F: TRAINER'S ZONE$"
