DewfordTown_Gym_Text_GymGuyGiveWater::
	.string "Hey, how's it going, Champion-\n"
	.string "bound {PLAYER}?\p"
    .string "Here, take this.$"

DewfordTown_Gym_Text_GymGuyFullBag::
    .string "Huh? Your Bag is too full.$"

DewfordTown_Gym_Text_GymGuyAdvice::
	.string "Dewford's Gym Leader Brawly commands\n"
	.string "Fighting-type Pokémon.\p"
	.string "Fighting-type attacks are strong\n"
    .string "against Normal, Rock, and Dark types.\p"
	.string "Use Psychic, Flying, and Fairy moves\n"
    .string "to push back his Fighting Pokémon.\p"
    .string "Brawly's strategy is straight-forward\n"
    .string "aggression, so counter him with\l"
    .string "your own offense.\p"
	.string "Hey, okay, go for it!$"

DewfordTown_Gym_Text_174F1E:: @ 8174F1E
	.string "Whoah! It's turned too bright in here!\p"
	.string "Your future is bright, too!$"

DewfordTown_Gym_Text_174F61:: @ 8174F61
	.string "Might is right!\n"
	.string "Come on!$"

DewfordTown_Gym_Text_174F7A:: @ 8174F7A
	.string "Not enough power...$"

DewfordTown_Gym_Text_174F8E:: @ 8174F8E
	.string "Your skill overcame my strength!\n"
	.string "Your technique is commendable!$"

DewfordTown_Gym_Text_174FCE:: @ 8174FCE
	.string "There's no need for Brawly to be\n"
	.string "involved!\p"
	.string "I'll crush you!$"

DewfordTown_Gym_Text_175009:: @ 8175009
	.string "But... How?\n"
	.string "How could I lose so easily?$"

DewfordTown_Gym_Text_175031:: @ 8175031
	.string "I'm not going to waste this loss.\n"
	.string "I'll use it to motivate me to train!\p"
	.string "One day I'll become a Gym Leader...\p"
	.string "No, I'll become the Pokémon League\n"
	.string "Champion!$"

DewfordTown_Gym_Text_1750C9:: @ 81750C9
	.string "Don't you dare brush me off!\n"
	.string "It's not my fault if you cry!$"

DewfordTown_Gym_Text_175104:: @ 8175104
	.string "Waaaaaaah!\n"
	.string "I lost!$"

DewfordTown_Gym_Text_175117:: @ 8175117
	.string "I battle in the dark to make my heart\n"
	.string "stronger.\p"
	.string "But because it's so dark, I can never\n"
	.string "see Brawly's face...$"

DewfordTown_Gym_Text_175182:: @ 8175182
	.string "I'm Brawly!\n"
	.string "Dewford's Gym Leader!\p"
	.string "I've been churned in the rough waves\n"
	.string "of these parts, and I've grown tough\l"
	.string "in the pitch-black cave!\p"
	.string "So you wanted to challenge me?\n"
	.string "Let me see what you're made of!$"

DewfordTown_Gym_Text_175246:: @ 8175246
	.string "Whoah, wow! You made a much bigger\n"
	.string "splash than I expected!\p"
	.string "You swamped me!\p"
	.string "Okay, you've got me.\n"
	.string "Take this Gym Badge!$"

DewfordTown_Gym_Text_1752BB:: @ 81752BB
	.string "{PLAYER} received the Knuckle Badge\n"
	.string "from Brawly.$"

DewfordTown_Gym_Text_1752E6:: @ 81752E6
	.string "The Knuckle Badge makes all Pokémon\n"
	.string "up to Level 30, even those you get in\l"
	.string "trades, obey without question.\p"
	.string "And, you'll be able to use the HM move\n"
	.string "Flash outside of battle.\p"
	.string "If you'd like, use this Technical\n"
	.string "Machine, too.$"

DewfordTown_Gym_Text_1753BF:: @ 81753BF
	.string "That TM08 contains Bulk Up.\p"
	.string "It's a move that raises both Attack\n"
	.string "and Defense stats.$"

DewfordTown_Gym_Text_175412:: @ 8175412
	.string "I can see your talent becoming a giant\n"
	.string "wave to cause a storm of astonishment\l"
	.string "among Trainers one day!$"

DewfordTown_Gym_Text_175477:: @ 8175477
	.string "DEWFORD TOWN POKéMON GYM$"

DewfordTown_Gym_Text_175490:: @ 8175490
	.string "DEWFORD TOWN POKéMON GYM\p"
	.string "BRAWLY'S CERTIFIED TRAINERS:\n"
	.string "{PLAYER}$"
